// El catálogo campo a campo del método de analíticas, cumplimiento, holgura de cada tramo y qué cuenta como cambio.
// Puro, sin React ni red. Los LÍMITES no se copian aquí (`ANALYTICS_METHOD_BOUNDS`).
// `catalogo.ts` une las tres partes y obliga en compilación a que no falte ninguna clave.


import type { CoachAnalyticsMethod } from '@fahybrid/shared/domain/analytics/metodo';
import type { CampoDescriptor } from './descriptores';

export const DESCRIPTORES_CUMPLIMIENTO_Y_CAMBIO = {
  // ── Cumplimiento ─────────────────────────────────────────────────────────
  cumplimiento_base: {
    tipo: 'seleccion',
    grupo: 'cumplimiento',
    etiqueta: 'Sobre qué se mide',
    ayuda: 'Qué cuenta el cumplimiento: sesiones hechas, tramos dentro de lo pedido, o carga hecha frente a la planificada.',
    opciones: [
      { value: 'sesiones', label: 'Sesiones hechas' },
      { value: 'tramos', label: 'Tramos dentro de lo pedido' },
      { value: 'carga', label: 'Carga hecha frente a planificada' },
    ],
  },
  cumplimiento_bien_pct: {
    tipo: 'numero',
    grupo: 'cumplimiento',
    etiqueta: 'A partir de aquí, bien',
    ayuda: 'Por encima de este porcentaje, el cumplimiento se enseña en verde.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },
  cumplimiento_regular_pct: {
    tipo: 'numero',
    grupo: 'cumplimiento',
    etiqueta: 'A partir de aquí, regular',
    ayuda: 'Entre este porcentaje y el de «bien» es regular; por debajo, malo.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },

  cumplimiento_sesion_bases: {
    tipo: 'orden',
    grupo: 'cumplimiento',
    etiqueta: 'Con qué se compara cada sesión',
    ayuda:
      'Para poner una sesión en verde, ámbar o rojo se compara lo hecho con lo planificado. Manda la primera de la lista que se sabe de las dos partes.',
    etiquetas: { carga: 'Carga', duracion: 'Duración', distancia: 'Distancia' },
  },
  cumplimiento_verde_min_pct: {
    tipo: 'numero',
    grupo: 'cumplimiento',
    etiqueta: 'Sesión cumplida desde',
    ayuda: 'Una sesión hecha con al menos este porcentaje de lo planificado sale en verde.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },
  cumplimiento_verde_max_pct: {
    tipo: 'numero',
    grupo: 'cumplimiento',
    etiqueta: 'Sesión cumplida hasta',
    ayuda: 'Y con como mucho este porcentaje: pasarse mucho de lo planificado ya no es cumplir.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },
  cumplimiento_ambar_min_pct: {
    tipo: 'numero',
    grupo: 'cumplimiento',
    etiqueta: 'Sesión desviada desde',
    ayuda: 'Entre este porcentaje y el de cumplida sale en ámbar (se quedó corto). Por debajo, o sin hacer, sale en rojo.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },
  cumplimiento_ambar_max_pct: {
    tipo: 'numero',
    grupo: 'cumplimiento',
    etiqueta: 'Sesión desviada hasta',
    ayuda: 'Entre el tope de cumplida y este porcentaje sale en ámbar (se pasó). Por encima, en rojo.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },

  // ── Cumplimiento: la holgura de cada tramo ───────────────────────────────
  holgura_ritmo_s_km: {
    tipo: 'numero',
    grupo: 'holgura',
    etiqueta: 'Ritmo al correr',
    ayuda: 'Cuánto puede salirse el ritmo de su banda y seguir dentro. Un objetivo de un solo ritmo se convierte en banda con esta holgura.',
    unidad: 's/km',
    decimales: 1,
    paso: 1,
  },
  holgura_split_s_500m: {
    tipo: 'numero',
    grupo: 'holgura',
    etiqueta: 'Ritmo en el ergómetro',
    ayuda: 'Lo mismo para el remo, el SkiErg y el BikeErg, en segundos cada 500 m.',
    unidad: 's/500 m',
    decimales: 1,
    paso: 1,
  },
  holgura_vatios_w: {
    tipo: 'numero',
    grupo: 'holgura',
    etiqueta: 'Potencia',
    ayuda: 'Cuántos vatios puede desviarse de la banda pedida y seguir dentro.',
    unidad: 'W',
    decimales: 0,
    paso: 1,
  },
  holgura_pulso_ppm: {
    tipo: 'numero',
    grupo: 'holgura',
    etiqueta: 'Pulso',
    ayuda: 'Cuántos latidos puede salirse de la zona o la banda de pulso pedida y seguir dentro.',
    unidad: 'ppm',
    decimales: 0,
    paso: 1,
  },
  holgura_rpe: {
    tipo: 'numero',
    grupo: 'holgura',
    etiqueta: 'Esfuerzo percibido (RPE)',
    ayuda: 'Cuántos puntos de la escala 1 a 10 puede desviarse el esfuerzo que cuenta el atleta y seguir dentro.',
    unidad: 'puntos',
    decimales: 1,
    paso: 0.5,
  },
  holgura_rir: {
    tipo: 'numero',
    grupo: 'holgura',
    etiqueta: 'Repeticiones en reserva (RIR)',
    ayuda: 'Cuántas repeticiones en reserva puede desviarse de las pedidas y seguir dentro.',
    unidad: 'reps',
    decimales: 1,
    paso: 0.5,
  },
  holgura_carga_pct: {
    tipo: 'numero',
    grupo: 'holgura',
    etiqueta: 'Carga de la barra',
    ayuda: 'Cuánto puede variar el peso puesto frente al prescrito. Con 0, tiene que ser el que pediste.',
    unidad: '%',
    decimales: 1,
    paso: 1,
  },
  holgura_dosis_pct: {
    tipo: 'numero',
    grupo: 'holgura',
    etiqueta: 'Dosis (distancia, tiempo, repeticiones, calorías)',
    ayuda: 'Cuánto puede variar lo hecho frente a lo prescrito. En el trabajo el fallo es quedarse corto, en la recuperación pasarse.',
    unidad: '%',
    decimales: 1,
    paso: 1,
  },

  // ── Qué cuenta como cambio (contra el periodo anterior) ─────────────────
  cambio_carga_pct: {
    tipo: 'numero',
    grupo: 'cambio',
    etiqueta: 'Cambio de carga que cuenta',
    ayuda: 'Variación de carga entre periodos a partir de la cual se avisa de un cambio.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },
  cambio_horas_pct: {
    tipo: 'numero',
    grupo: 'cambio',
    etiqueta: 'Cambio de horas que cuenta',
    ayuda: 'Variación de horas entrenadas entre periodos a partir de la cual cuenta como cambio.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },
  cambio_forma_tss: {
    tipo: 'numero',
    grupo: 'cambio',
    etiqueta: 'Cambio de forma que cuenta',
    ayuda: 'Variación de forma entre periodos a partir de la cual cuenta como cambio.',
    unidad: 'puntos',
    decimales: 0,
    paso: 1,
  },
  cambio_frescura_tss: {
    tipo: 'numero',
    grupo: 'cambio',
    etiqueta: 'Cambio de frescura que cuenta',
    ayuda: 'Variación de frescura entre periodos a partir de la cual cuenta como cambio.',
    unidad: 'puntos',
    decimales: 0,
    paso: 1,
  },
  cambio_variabilidad_pct: {
    tipo: 'numero',
    grupo: 'cambio',
    etiqueta: 'Cambio de variabilidad que cuenta',
    ayuda: 'Variación de variabilidad cardiaca entre periodos a partir de la cual cuenta como cambio.',
    unidad: '%',
    decimales: 0,
    paso: 1,
  },
  cambio_pulso_reposo_bpm: {
    tipo: 'numero',
    grupo: 'cambio',
    etiqueta: 'Cambio de pulso en reposo que cuenta',
    ayuda: 'Variación de pulso en reposo entre periodos a partir de la cual cuenta como cambio.',
    unidad: 'ppm',
    decimales: 0,
    paso: 1,
  },
  cambio_sueno_horas: {
    tipo: 'numero',
    grupo: 'cambio',
    etiqueta: 'Cambio de sueño que cuenta',
    ayuda: 'Variación de horas de sueño entre periodos a partir de la cual cuenta como cambio.',
    unidad: 'horas',
    decimales: 1,
    paso: 0.5,
  },
  cambio_cumplimiento_pts: {
    tipo: 'numero',
    grupo: 'cambio',
    etiqueta: 'Cambio de cumplimiento que cuenta',
    ayuda: 'Variación del porcentaje de cumplimiento entre periodos, en puntos, a partir de la cual cuenta como cambio.',
    unidad: 'puntos',
    decimales: 0,
    paso: 1,
  },
} satisfies Partial<Record<keyof CoachAnalyticsMethod, CampoDescriptor>>;
