// Nombre Material Symbols → icono Lucide. Es el diccionario que deja a
// `<MIcon name="…">` seguir funcionando igual mientras dibuja SVG de Lucide en
// vez de la fuente variable de 3,9 MB (auditoría E, §2.8).
//
// Cubre TODOS los nombres que el repo pasa a MIcon: literales en `name=`, props
// `icon` / `icono` y los mapas `*_ICON` que acaban en MIcon. Un nombre que no
// esté aquí pinta un glifo neutro y avisa en desarrollo (ver MIcon.tsx): al
// añadir un icono nuevo, añádelo aquí o importa el componente de Lucide directo.
//
// `auto_awesome` (las «chispas» de IA) va a un glifo neutro a propósito:
// CLAUDE.md prohíbe los clichés de app de IA.

import type { LucideIcon } from 'lucide-react';
import {
  Archive, ArrowDown, ArrowLeft, ArrowLeftRight, ArrowRight, ArrowRightLeft, ArrowUp,
  ArrowUpRight, AudioLines, BadgeCheck, Ban, Bandage, Banknote, BatteryWarning, Bell,
  BellRing, Bike, Book, BookOpen, BookmarkPlus, Brain, Calendar, CalendarCheck,
  CalendarClock, CalendarCog, CalendarDays, CalendarPlus, CalendarRange, CalendarSync,
  CalendarX, Camera, ChartColumn, ChartGantt, ChartLine, ChartNoAxesColumn, ChartSpline,
  Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsDown,
  ChevronsDownUp, ChevronsUpDown, Circle, CircleAlert, CircleCheck, CircleCheckBig,
  CircleDot, CircleEllipsis, CircleMinus, CircleOff, CirclePause, CirclePlay, CirclePlus,
  CircleQuestionMark, CircleX, ClipboardList, ClipboardX, CloudOff,
  Columns3, Copy, CopyPlus, CreditCard, Download, Droplet, Dumbbell, Ellipsis, ExternalLink, Eye,
  EyeOff, FileCheck, FileText, FileUp, Film, Flag, Flame, Flower2, Footprints, Frown,
  FunnelX, Gauge, GraduationCap, GripVertical, Hammer, Hand, HeartPulse, History,
  Hourglass, IdCard, Image, ImagePlus, Info, Layers, LayoutDashboard, LayoutGrid,
  LayoutTemplate, Library, Lightbulb, Link, List, ListChecks, ListPlus, LoaderCircle,
  LocateFixed, Lock, LogOut, Mail, MailCheck, Maximize2, Medal, Megaphone,
  MessageSquare, MessageSquareCheck, MessageSquarePlus, MessageSquareText,
  MessagesSquare, Mic, Minus, MonitorPlay, Moon, Mountain, MountainSnow, Network,
  NotebookPen, NotepadText, Package, Paperclip, Pause, PenLine, Pencil, PersonStanding,
  Phone, Play, Plus, Quote, RefreshCw, RefreshCwOff, Repeat, Reply, Rocket, RotateCcw,
  Route, Rows3, Save, ScanSearch, ScanText, Scissors, Search, SearchX, Send, Settings,
  Shapes, Shield, ShieldPlus, ShieldUser, Signal, SkipForward, SlidersHorizontal, Square,
  SquareCheck, SquarePen, SquareStack, StickyNote, Store, Sun, Target, Timer, Trash2,
  TrendingDown, TrendingUp, Triangle, TriangleAlert, Trophy, Undo2, Upload, User,
  UserCheck, UserPen, UserPlus, UserSearch, UserX, Users, UsersRound, Video, Warehouse,
  Watch, WavesHorizontal, Wrench, X, Zap,
} from 'lucide-react';

export const MICON_MAP: Record<string, LucideIcon> = {
  account_tree: Network,
  add: Plus,
  add_circle: CirclePlus,
  add_comment: MessageSquarePlus,
  add_photo_alternate: ImagePlus,
  airline_seat_legroom_extra: PersonStanding,
  analytics: ChartColumn,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assignment: ClipboardList,
  assignment_ind: IdCard,
  assignment_late: ClipboardX,
  attach_file: Paperclip,
  auto_awesome: CircleDot,
  auto_awesome_motion: SquareStack,
  auto_fix: Wrench,
  auto_fix_high: Wrench,
  bar_chart: ChartNoAxesColumn,
  battery_alert: BatteryWarning,
  bedtime: Moon,
  block: Ban,
  bolt: Zap,
  book: Book,
  bookmark_add: BookmarkPlus,
  build: Hammer,
  calendar_add_on: CalendarPlus,
  calendar_clock: CalendarClock,
  calendar_month: Calendar,
  calendar_view_week: CalendarRange,
  call: Phone,
  campaign: Megaphone,
  cancel: CircleX,
  change_history: Triangle,
  chat: MessageSquare,
  check: Check,
  check_box: SquareCheck,
  check_box_outline_blank: Square,
  check_circle: CircleCheck,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_off: CloudOff,
  compare_arrows: ArrowLeftRight,
  content_copy: Copy,
  content_cut: Scissors,
  credit_card_off: CreditCard,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  dashboard_customize: LayoutTemplate,
  date_range: CalendarRange,
  delete: Trash2,
  description: FileText,
  directions_bike: Bike,
  directions_run: Footprints,
  do_not_disturb_on: CircleMinus,
  do_not_step: CircleOff,
  document_scanner: ScanText,
  done: Check,
  done_all: CheckCheck,
  downhill_skiing: MountainSnow,
  download: Download,
  download_done: FileCheck,
  drag_indicator: GripVertical,
  draw: PenLine,
  edit: Pencil,
  edit_calendar: CalendarCog,
  edit_note: NotebookPen,
  edit_square: SquarePen,
  error: CircleAlert,
  error_outline: CircleAlert,
  event: Calendar,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  event_repeat: CalendarSync,
  event_upcoming: CalendarClock,
  exercise: Dumbbell,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  filter_alt_off: FunnelX,
  fitness_center: Dumbbell,
  flag: Flag,
  footprint: Footprints,
  format_list_bulleted: List,
  format_quote: Quote,
  forum: MessagesSquare,
  graphic_eq: AudioLines,
  grid_view: LayoutGrid,
  group: Users,
  groups: UsersRound,
  healing: Bandage,
  health_and_safety: ShieldPlus,
  help: CircleQuestionMark,
  history: History,
  hourglass_empty: Hourglass,
  hourglass_top: Hourglass,
  how_to_reg: UserCheck,
  image: Image,
  info: Info,
  insights: ChartSpline,
  inventory_2: Package,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  keyboard_double_arrow_down: ChevronsDown,
  landscape: Mountain,
  layers: Layers,
  leaderboard: Trophy,
  library_add: CopyPlus,
  library_books: Library,
  light: Sun,
  light_mode: Sun,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  mark_chat_read: MessageSquareCheck,
  mark_email_read: MailCheck,
  menu_book: BookOpen,
  mic: Mic,
  monitor_heart: HeartPulse,
  monitoring: ChartLine,
  more_horiz: Ellipsis,
  movie: Film,
  my_location: LocateFixed,
  neurology: Brain,
  north_east: ArrowUpRight,
  notes: NotepadText,
  notifications: Bell,
  notifications_active: BellRing,
  opacity: Droplet,
  open_in_full: Maximize2,
  open_in_new: ExternalLink,
  pan_tool: Hand,
  pause: Pause,
  pause_circle: CirclePause,
  payments: Banknote,
  pedal_bike: Bike,
  pending: CircleEllipsis,
  person: User,
  person_add: UserPlus,
  person_edit: UserPen,
  person_off: UserX,
  person_search: UserSearch,
  personal_injury: Bandage,
  photo: Image,
  photo_camera: Camera,
  picture_as_pdf: FileText,
  play_arrow: Play,
  play_circle: CirclePlay,
  playlist_add: ListPlus,
  priority_high: CircleAlert,
  progress_activity: LoaderCircle,
  psychology: Brain,
  query_stats: ScanSearch,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  rate_review: MessageSquareText,
  refresh: RefreshCw,
  remove: Minus,
  remove_circle_outline: CircleMinus,
  repeat: Repeat,
  replay: RotateCcw,
  reply: Reply,
  restart_alt: RotateCcw,
  rocket_launch: Rocket,
  route: Route,
  rowing: WavesHorizontal,
  save: Save,
  school: GraduationCap,
  search: Search,
  search_off: SearchX,
  self_improvement: PersonStanding,
  send: Send,
  sentiment_dissatisfied: Frown,
  settings: Settings,
  shield: Shield,
  shield_person: ShieldUser,
  show_chart: ChartLine,
  signal_cellular_alt: Signal,
  skip_next: SkipForward,
  smart_display: MonitorPlay,
  spa: Flower2,
  speed: Gauge,
  sports_gymnastics: PersonStanding,
  sports_score: Medal,
  stacks: Layers,
  sticky_note_2: StickyNote,
  stop: Square,
  storefront: Store,
  swap_horiz: ArrowLeftRight,
  sync: RefreshCw,
  sync_alt: ArrowRightLeft,
  sync_problem: RefreshCwOff,
  table_rows: Rows3,
  target: Target,
  task_alt: CircleCheckBig,
  timer: Timer,
  tips_and_updates: Lightbulb,
  today: CalendarDays,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  undo: Undo2,
  unfold_less: ChevronsDownUp,
  unfold_more: ChevronsUpDown,
  upload: Upload,
  upload_file: FileUp,
  verified: BadgeCheck,
  videocam: Video,
  view_timeline: ChartGantt,
  view_week: Columns3,
  visibility: Eye,
  visibility_off: EyeOff,
  warehouse: Warehouse,
  warning: TriangleAlert,
  watch: Watch,
  wb_sunny: Sun,
  whatshot: Flame,
  widgets: Shapes,
};
