// Quién es dueño de cada tabla — la base del check de ámbito (DECISIONS
// 2026-09-24 «check de coach en CI ya, RLS antes del coach 20»).
//
//   club        la fila es de UN club. Una consulta que la toca tiene que filtrar
//               por el coach (`…coach_id` comparado) o decir por qué su ámbito es
//               seguro (`// tenancy: <razón>`). `via` es el camino de propiedad
//               hasta el coach: lo que una política RLS tendrá que recorrer.
//   usuario     la fila es de UN usuario (sesiones, avisos). No es dato de club;
//               queda fuera de este check y dentro del de RLS.
//   plataforma  no es de nadie (diario del migrador, límites, login antes de saber
//               quién eres).
//
// Generado del esquema real (143 tablas, 0272) y revisado a mano. Una tabla nueva
// sin clasificar hace fallar `ambito-de-club.test.ts`: se clasifica aquí.

export type Ambito =
  | { clase: 'club'; via: string }
  | { clase: 'usuario' }
  | { clase: 'plataforma'; porque: string };

export const TABLAS: Record<string, Ambito> = {
  account_deletion_jobs: { clase: 'usuario' },
  apns_push_tokens: { clase: 'club', via: 'device_id → devices' },
  app_feedback: { clase: 'club', via: 'athlete_user_id → athletes.user_id' },
  appointments: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_benchmarks: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_coach_notes: { clase: 'club', via: 'coach_id' },
  athlete_daily_readiness_snapshots: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_emphasis: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_invitations: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_invoices: { clase: 'club', via: 'subscription_id → subscriptions' },
  athlete_level_criteria: { clase: 'club', via: 'coach_id' },
  athlete_levels: { clase: 'club', via: 'coach_id' },
  athlete_month_assignments: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_pause_requests: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_pauses: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_sequence_progress: { clase: 'club', via: 'coach_id' },
  athlete_strength_maxes: { clase: 'club', via: 'athlete_id → athletes' },
  athlete_zone_profiles: { clase: 'club', via: 'athlete_id → athletes' },
  athletes: { clase: 'club', via: 'coach_id' },
  audit_log: { clase: 'plataforma', porque: 'registro de la plataforma' },
  biometric_streams: { clase: 'club', via: 'athlete_id → athletes' },
  block_exercises: { clase: 'club', via: 'block_id → blocks' },
  blocks: { clase: 'club', via: 'coach_id' },
  catalog_sync_runs: { clase: 'plataforma', porque: 'sincronización del catálogo común de carreras' },
  chat_messages: { clase: 'club', via: 'thread_id → chat_threads' },
  chat_threads: { clase: 'club', via: 'coach_id' },
  coach_alert_overrides: { clase: 'club', via: 'coach_id' },
  coach_allowlist: { clase: 'club', via: 'coach_id' },
  coach_analytics_method: { clase: 'club', via: 'coach_id' },
  coach_assign_batch_cursor_changes: { clase: 'club', via: 'batch_item_id → coach_assign_batch_items' },
  coach_assign_batch_items: { clase: 'club', via: 'athlete_id → athletes' },
  coach_assign_batch_microcycle_changes: { clase: 'club', via: 'batch_item_id → coach_assign_batch_items' },
  coach_assign_batch_receipt_changes: { clase: 'club', via: 'athlete_id → athletes' },
  coach_assign_batch_session_changes: { clase: 'club', via: 'athlete_id → athletes' },
  coach_assign_batch_week_changes: { clase: 'club', via: 'batch_item_id → coach_assign_batch_items' },
  coach_assign_batches: { clase: 'club', via: 'coach_id' },
  coach_attention_items: { clase: 'club', via: 'coach_id' },
  coach_availability: { clase: 'club', via: 'coach_id' },
  coach_availability_exceptions: { clase: 'club', via: 'coach_id' },
  coach_calibration_tests: { clase: 'club', via: 'coach_id' },
  coach_communication_item_marks: { clase: 'club', via: 'recipient_id → coach_communication_recipients' },
  coach_communication_item_segments: { clase: 'club', via: 'item_id → coach_communication_items' },
  coach_communication_items: { clase: 'club', via: 'communication_id → coach_communications' },
  coach_communication_recipients: { clase: 'club', via: 'athlete_id → athletes' },
  coach_communications: { clase: 'club', via: 'coach_id' },
  coach_entitlements: { clase: 'club', via: 'coach_id' },
  coach_exercise_overrides: { clase: 'club', via: 'coach_id' },
  coach_exercise_synonyms: { clase: 'club', via: 'coach_id' },
  coach_google_connections: { clase: 'club', via: 'coach_id' },
  coach_guidance: { clase: 'club', via: 'coach_id' },
  coach_hr_method: { clase: 'club', via: 'coach_id' },
  coach_import_defaults: { clase: 'club', via: 'coach_id' },
  coach_jump_method: { clase: 'club', via: 'coach_id' },
  coach_key_markers: { clase: 'club', via: 'coach_id' },
  coach_mass_adjustment_patterns: { clase: 'club', via: 'coach_id' },
  coach_mass_adjustment_targets: { clase: 'club', via: 'athlete_id → athletes' },
  coach_mass_adjustments: { clase: 'club', via: 'coach_id' },
  coach_members: { clase: 'club', via: 'coach_id' },
  coach_method_interview: { clase: 'club', via: 'coach_id' },
  coach_methodology: { clase: 'club', via: 'coach_id' },
  coach_movement_policy: { clase: 'club', via: 'coach_id' },
  coach_onboarding_forms: { clase: 'club', via: 'coach_id' },
  coach_running_thresholds: { clase: 'club', via: 'coach_id' },
  coach_saved_views: { clase: 'club', via: 'coach_id' },
  coach_signal_thresholds: { clase: 'club', via: 'coach_id' },
  coach_test_results: { clase: 'club', via: 'test_id → coach_calibration_tests' },
  coach_test_schedule: { clase: 'club', via: 'test_id → coach_calibration_tests' },
  coach_weekly_reviews: { clase: 'club', via: 'coach_id' },
  coaches: { clase: 'club', via: 'raíz: el propio club (id = coach)' },
  coros_mcp_oauth_client: { clase: 'plataforma', porque: 'cliente OAuth de la plataforma con COROS' },
  daily_checkins: { clase: 'club', via: 'athlete_id → athletes' },
  devices: { clase: 'club', via: 'athlete_id → athletes' },
  dobles_live_status: { clase: 'club', via: 'athlete_id → athletes' },
  dobles_simulations: { clase: 'club', via: 'created_by_coach_id' },
  doubles_pairs: { clase: 'club', via: 'coach_id' },
  email_login_codes: { clase: 'plataforma', porque: 'login por email, antes de saber el coach' },
  events: { clase: 'club', via: 'created_by_coach_id / athlete_id (el catálogo común: created_by_coach_id null)' },
  exercise_aliases: { clase: 'club', via: 'exercise_id → exercises' },
  exercises: { clase: 'club', via: 'coach_id' },
  garmin_oauth_tokens: { clase: 'club', via: 'athlete_id → athletes' },
  google_oauth_tokens: { clase: 'club', via: 'LEGADO global (0254 lo sustituye por coach_google_connections): cualquier lectura es un agujero' },
  healthkit_sync_state: { clase: 'club', via: 'athlete_id → athletes' },
  import_jobs: { clase: 'club', via: 'athlete_id → athletes' },
  injuries: { clase: 'club', via: 'athlete_id → athletes' },
  injury_updates: { clase: 'club', via: 'injury_id → injuries' },
  jump_attempts: { clase: 'club', via: 'athlete_id → athletes' },
  lead_nurture_log: { clase: 'club', via: 'lead_id → leads' },
  lead_status_events: { clase: 'club', via: 'lead_id → leads' },
  leads: { clase: 'club', via: 'coach_id' },
  llm_invocations: { clase: 'club', via: 'coach_id' },
  magic_link_tokens: { clase: 'plataforma', porque: 'login por email, antes de saber el coach' },
  methodology_blocks: { clase: 'club', via: 'coach_id' },
  methodology_chunks: { clase: 'club', via: 'document_id → methodology_documents' },
  methodology_documents: { clase: 'club', via: 'coach_id' },
  methodology_groups: { clase: 'plataforma', porque: 'lista común de grupos metodológicos' },
  methodology_nutrition_rules: { clase: 'club', via: 'coach_id' },
  methodology_rules: { clase: 'club', via: 'coach_id' },
  methodology_station_strategy: { clase: 'club', via: 'coach_id' },
  methodology_substitutions: { clase: 'club', via: 'coach_id' },
  methodology_tests: { clase: 'club', via: 'coach_id' },
  methodology_weekly_structure: { clase: 'club', via: 'coach_id' },
  methodology_zones: { clase: 'club', via: 'coach_id' },
  microcycles: { clase: 'club', via: 'athlete_id → athletes' },
  monthly_block_proposals: { clase: 'club', via: 'athlete_id → athletes' },
  notifications: { clase: 'usuario' },
  nutrition_entries: { clase: 'club', via: 'athlete_id → athletes' },
  partner_invitations: { clase: 'club', via: 'inviter_user_id → athletes.user_id' },
  program_month_templates: { clase: 'club', via: 'coach_id' },
  program_month_weeks: { clase: 'club', via: 'month_template_id → program_month_templates' },
  program_sequence_items: { clase: 'club', via: 'sequence_id → program_sequences' },
  program_sequences: { clase: 'club', via: 'coach_id' },
  program_week_templates: { clase: 'club', via: 'coach_id' },
  race_partners: { clase: 'club', via: 'race_id → races' },
  race_predictions: { clase: 'club', via: 'athlete_id → athletes' },
  races: { clase: 'club', via: 'athlete_id → athletes' },
  rate_limit_buckets: { clase: 'plataforma', porque: 'límites por IP/clave' },
  schema_migrations: { clase: 'plataforma', porque: 'diario del migrador' },
  segment_executions: { clase: 'club', via: 'execution_id → workout_executions' },
  segment_zone_seconds: { clase: 'club', via: 'segment_execution_id → segment_executions' },
  session_reports: { clase: 'club', via: 'coach_id' },
  sessions: { clase: 'usuario' },
  set_executions: { clase: 'club', via: 'segment_execution_id → segment_executions' },
  stripe_customers: { clase: 'club', via: 'athlete_id → athletes' },
  stripe_subscriptions: { clase: 'club', via: 'athlete_id → athletes' },
  subscriptions: { clase: 'club', via: 'user_id → athletes.user_id' },
  template_blocks: { clase: 'club', via: 'template_id → templates' },
  template_segments: { clase: 'club', via: 'template_id → templates' },
  templates: { clase: 'club', via: 'coach_id' },
  user_roles: { clase: 'usuario' },
  users: { clase: 'usuario' },
  visit_counts: { clase: 'plataforma', porque: 'analítica anónima de la landing' },
  visit_seen: { clase: 'plataforma', porque: 'analítica anónima de la landing' },
  wearable_activity_confirmations: { clase: 'club', via: 'athlete_id → athletes' },
  wearable_connections: { clase: 'club', via: 'athlete_id → athletes' },
  wearable_fit_quota: { clase: 'club', via: 'athlete_id → athletes' },
  web_push_subscriptions: { clase: 'usuario' },
  week_adjustment_proposals: { clase: 'club', via: 'athlete_id → athletes' },
  weekly_plans: { clase: 'club', via: 'athlete_id → athletes' },
  workout_assignments: { clase: 'club', via: 'athlete_id → athletes' },
  workout_executions: { clase: 'club', via: 'athlete_id → athletes' },
  workout_routes: { clase: 'club', via: 'execution_id → workout_executions' },
  workout_sensor_captures: { clase: 'club', via: 'athlete_id → athletes' },
  workout_traces: { clase: 'club', via: 'execution_id → workout_executions' },
};
