import Foundation

// Service + Codable models for the Carreras (performance/race) hub: the IA
// weakness report, station benchmarks, and running splits of the last singles race.
//
// LIVE: the race-derived endpoints now ship. fetchOverview hits
// `GET /api/athlete/race-context`, fetchStationDetail hits
// `GET /api/athlete/stations/{station}`, fetchRunningAnalysis hits
// `GET /api/athlete/running-analysis`, and importRace POSTs an official HYROX
// detail link to `POST /api/athlete/race-results/import`. Each read degrades to
// nil on no-bearer / request failure (so the views render honest empty states),
// and each endpoint is itself honest-empty when the athlete has no imported race.
//
// Este fichero SOLO posee el contrato derivado de carreras. La analítica de
// entrenamiento se lee en la pestaña ANALÍTICAS, por su propio endpoint por
// sección (`AnalyticsService`); el resumen suelto que se pedía aquí no lo leía
// ninguna pantalla y se retiró.
//
// Snake_case Codable keys match the project convention (Swift Codable mirrors
// the API's snake_case responses).

// MARK: - Models

/// La carrera de la que salen los bloques del análisis: la última carrera INDIVIDUAL con
/// resultado. Solo lo que hace falta para nombrarla y ubicarla; su tiempo, sus parciales y su
/// puesto los lleva el hub (`ImportedRace`), que es la fuente única de las carreras pasadas.
struct CarreraDelAnalisis: Codable, Identifiable, Hashable {
    /// `races.id` como texto (el cable lo manda así).
    let id: String
    let event_name: String
    /// ISO `YYYY-MM-DD`, o «Fecha por confirmar» cuando el servidor no sabe la fecha.
    let date: String

    // `.convertFromSnakeCase` reescribe cada clave del cable a camelCase ANTES de casar con
    // la CodingKey: una propiedad snake_case de varias palabras no casaría nunca y, siendo no
    // opcional, tiraría abajo el decode entero. Se mapea a la forma ya convertida.
    enum CodingKeys: String, CodingKey {
        case id
        case event_name = "eventName"
        case date
    }
}

/// The IA weakness report attached to a race.
struct RaceIAReport: Codable, Hashable {
    /// Free-ish prose of what to prioritize (generated by the methodology IA).
    let summary: String
    /// Recommended training-group chips, e.g. ["G03 · Ergómetros", …].
    let recommended_groups: [String]

    // `.convertFromSnakeCase` rewrites `recommended_groups` → `recommendedGroups`
    // before matching, so map the multi-word key to the post-conversion form.
    enum CodingKeys: String, CodingKey {
        case summary
        case recommended_groups = "recommendedGroups"
    }
}

/// A station benchmark comparison row (athlete vs the field).
struct StationBenchmark: Codable, Identifiable, Hashable {
    /// `station_<índice canónico>`: el índice de la estación va en el id.
    let id: String
    /// Station name, e.g. "Sled Push".
    let station: String
    /// Athlete's time for the station, pre-formatted.
    let time: String?
    /// Signed delta vs the athlete's trained level, pre-formatted "+0:42" / "−0:08".
    let delta: String?
    /// Normalized bar fraction 0…1. NIL when the race carries no placing for the
    /// station: there is then no bar to draw, and drawing one at half height
    /// would insinuate a position nobody measured.
    let fraction: Double?
    /// Field-relative verdict: "better" | "slightly_worse" | "worse". NIL for the
    /// same reason as `fraction` — the time is still real and still shown.
    let severity: String?
}

/// Per-km running split for the pace chart.
struct RunningSplit: Codable, Identifiable, Hashable {
    let id: String
    /// Km index label, e.g. "k1".
    let label: String
    /// Pace time for the km, pre-formatted "3:45".
    let pace: String?
    /// Normalized bar height 0…1.
    let height: Double
    /// "better" | "slightly_worse" | "worse".
    let severity: String
}

/// The bundle the Carreras hub loads in one shot.
///
/// La lista de carreras anteriores (`history`) YA NO se decodifica: llegaba con la forma de
/// `RaceHistoryItem` y se leía como el resumen de la última, así que cada fila fallaba, la lista
/// quedaba vacía y la Evolución no se pintaba nunca. Las carreras pasadas salen del hub
/// (`GET /athlete/races`, `ImportedRace`): una sola fuente. Tampoco `station_comparison_note`:
/// «no hay ni un puesto por estación» se deduce de la propia lista.
struct CarrerasOverview: Codable, Hashable {
    let last_race: CarreraDelAnalisis?
    let ia_report: RaceIAReport?
    // AUDIT-B3 — a malformed row is dropped, not the whole Carreras hub.
    @LossyArray var station_benchmarks: [StationBenchmark]
    @LossyArray var running_splits: [RunningSplit]
    /// La caída de ritmo de la segunda mitad, dicha en prosa por el servidor («… (+18s/km)»).
    /// El número se lee de aquí una vez (`CaidaDeRitmoCable`); el texto lo escribe la vista.
    let pace_drop_note: String?

    // `.convertFromSnakeCase` rewrites each multi-word wire key (last_race →
    // lastRace, …) before matching; the snake_case property's default CodingKey
    // would never match. Map each to the post-conversion form so the bundle
    // decodes while the views keep referencing snake_case properties.
    enum CodingKeys: String, CodingKey {
        case last_race = "lastRace"
        case ia_report = "iaReport"
        case station_benchmarks = "stationBenchmarks"
        case running_splits = "runningSplits"
        case pace_drop_note = "paceDropNote"
    }
}

// MARK: - Service

enum CarrerasService {
    /// Load the Carreras hub overview for the authenticated athlete.
    ///
    /// LIVE: `GET /api/athlete/race-context` builds the bundle from the athlete's
    /// IMPORTED HYROX results — the last singles race, per-station benchmarks, the
    /// 8×1 km running splits and an optional pace-drop note. The endpoint is
    /// honest-empty (every field null/empty) when the athlete has no imported race
    /// yet. THROWS on failure: AppDataStore's SWR engine needs the error so a failed
    /// revalidation KEEPS the last good cached overview (and the offline disk
    /// snapshot) rather than overwriting it with an empty result.
    static func fetchOverviewThrowing(bearer: String) async throws -> CarrerasOverview {
        try await APIClient.shared.get(
            path: "api/athlete/race-context",
            bearer: bearer
        )
    }

    /// Import an official HYROX result for the authenticated athlete.
    ///
    /// `POST /api/athlete/race-results/import` with `{ result_url }`. The server
    /// fetches + parses the HYROX detail page and upserts the athlete's `races`
    /// row (idempotent per HYROX idp — re-pasting refreshes). On success the tab
    /// asks the store to reconcile (`racesMutated`) to surface the new race.
    ///
    /// Throws `CarrerasImportError` with an athlete-readable message keyed off the
    /// server's error code, or a network/decoding wrapper, so the sheet can show
    /// an honest reason rather than a generic failure.
    static func importRace(resultURL: String, bearer: String?) async throws {
        guard let bearer else { throw CarrerasImportError.unauthorized }
        do {
            // We don't need the parsed result on-device; a successful 201 is the
            // signal to refresh. Decode into Empty so an unexpected body shape
            // can never fail the import after the server already stored it.
            let _: Empty = try await APIClient.shared.post(
                path: "api/athlete/race-results/import",
                body: HyroxImportBody(result_url: resultURL),
                bearer: bearer
            )
        } catch let error as APIError {
            throw CarrerasImportError(apiError: error)
        } catch is CancellationError {
            throw CancellationError()
        } catch {
            // `session.data(for:)` surfaces transport failures (offline, timeout,
            // DNS) as URLError BEFORE APIClient wraps them — treat those as a
            // reachability problem, not a bad link.
            throw CarrerasImportError.hyroxUnreachable
        }
    }

    /// Detail for a single station across the athlete's races.
    ///
    /// LIVE: `GET /api/athlete/stations/{station}` computes the deep-dive from the
    /// athlete's imported HYROX results — last time vs their own best (+ delta,
    /// severity, percentile from station rank / field size), the trend across
    /// imported races, sub-metrics, the methodology groups that train it, and the
    /// technique video when seeded. IA recommendation is deferred (null). The
    /// `{station}` segment is the station LABEL (percent-encoded path segment);
    /// the backend resolves it tolerantly to the canonical HYROX station. Returns
    /// nil on no bearer or request failure so the view renders its empty state;
    /// an empty (but non-nil) detail is returned when there are simply no races.
    static func fetchStationDetail(station: String, bearer: String?) async -> StationDetail? {
        guard let bearer else { return nil }
        let encoded = station.addingPercentEncoding(
            withAllowedCharacters: .urlPathAllowed
        ) ?? station
        do {
            return try await APIClient.shared.get(
                path: "api/athlete/stations/\(encoded)",
                bearer: bearer
            )
        } catch {
            return nil
        }
    }

    /// Running deep-dive metrics (threshold pace, VO₂ est., best 1 km, pace
    /// zones, threshold progression, the training that works it).
    ///
    /// LIVE: `GET /api/athlete/running-analysis` computes the bundle from the
    /// athlete's stored run segments + a Jack-Daniels VDOT off their 5K
    /// benchmark. Fields the system can't measure yet (threshold/VO₂/zones with
    /// no 5K, training links) come back null / empty and the views render honest
    /// empty states.
    /// It THROWS so the AppDataStore's SWR engine keeps the last-good cached
    /// analysis (offline-first) when a revalidation fails.
    static func fetchRunningAnalysisThrowing(bearer: String) async throws -> RunningAnalysis? {
        try await APIClient.shared.get(
            path: "api/athlete/running-analysis",
            bearer: bearer
        )
    }

    /// Load the unified races hub — future objectives + past results — in one
    /// shot. `GET /api/athlete/races` is the SOURCE OF TRUTH for both the PRÓXIMAS
    /// countdown list and the PASADAS history (which the hub write-through caches
    /// locally). Returns nil on no-bearer / request failure so the view keeps its
    /// cached history and honest empty states rather than erroring.
    static func fetchRaces(bearer: String?) async -> RacesHubResponse? {
        guard let bearer else { return nil }
        return try? await fetchRacesThrowing(bearer: bearer)
    }

    /// Throwing variant of `fetchRaces` — same `GET /api/athlete/races`, but it
    /// propagates the error instead of degrading to nil. AppDataStore's SWR engine
    /// needs the throw so a failed revalidation KEEPS the last good cached hub
    /// (and the offline disk snapshot) instead of wiping both lists. The
    /// non-throwing wrapper above preserves the "degrade to nil" contract its
    /// other callers (e.g. Perfil) rely on. One endpoint path — no parallel fetch.
    static func fetchRacesThrowing(bearer: String) async throws -> RacesHubResponse {
        try await APIClient.shared.get(
            path: "api/athlete/races",
            bearer: bearer
        )
    }

    /// Remove ONE future objective (target OR secondary/tune-up) from the
    /// athlete's plan. `DELETE /api/athlete/races/target/{race_id}` works for any
    /// upcoming race. No request body. Throws `HyresultImportError` so the hub can
    /// surface an honest reason (mapped to removal-appropriate copy at the call
    /// site, since the error's own messages are import-flavored).
    static func deleteObjective(raceId: Int, bearer: String?) async throws {
        guard let bearer else { throw HyresultImportError.unauthorized }
        do {
            let _: Empty = try await APIClient.shared.delete(
                path: "api/athlete/races/target/\(raceId)",
                body: Optional<Empty>.none,
                bearer: bearer
            )
        } catch let error as APIError {
            throw HyresultImportError(apiError: error)
        } catch is CancellationError {
            throw CancellationError()
        } catch {
            throw HyresultImportError.unreachable
        }
    }

    /// Promote ONE existing upcoming race to the athlete's PRIMARY objective
    /// ('target'). `POST /api/athlete/races/target/{race_id}` flips its priority
    /// in place and demotes any prior target to 'secondary' (single-target
    /// invariant, enforced server-side). No request body — the race is already on
    /// the calendar. On success the hub should re-fetch so the badges AND Inicio's
    /// main countdown reflect the new primary. Throws `HyresultImportError` so the
    /// hub can surface an honest reason (mapped to promote-appropriate copy at the
    /// call site, since the error's own messages are import-flavored).
    static func makePrimaryObjective(raceId: Int, bearer: String?) async throws {
        guard let bearer else { throw HyresultImportError.unauthorized }
        do {
            let _: Empty = try await APIClient.shared.post(
                path: "api/athlete/races/target/\(raceId)",
                body: Empty(),
                bearer: bearer
            )
        } catch let error as APIError {
            throw HyresultImportError(apiError: error)
        } catch is CancellationError {
            throw CancellationError()
        } catch {
            throw HyresultImportError.unreachable
        }
    }
}

// MARK: - Import request + errors

/// Request body for `POST /api/athlete/race-results/import`. The encoder applies
/// `.convertToSnakeCase`; an all-lowercase `result_url` has no case boundary so
/// it is emitted verbatim, matching the server's `hyroxImportInput` Zod schema.
private struct HyroxImportBody: Encodable {
    let result_url: String
}

/// HYROX detail-page host the athlete must paste from. Single source for the
/// client-side pre-flight check + the empty-state copy; the server re-validates
/// this exact host (SSRF allowlist) so it is authoritative — this constant only
/// gives the athlete instant feedback for the obvious wrong-link case.
enum HyroxImport {
    static let resultsHost = "results.hyrox.com"

    /// Lightweight client-side check that a pasted string LOOKS like a HYROX
    /// results detail link: an https URL whose host is exactly results.hyrox.com.
    /// Deliberately permissive about the query (season/idp/event are validated
    /// server-side) — we only catch the clearly-not-HYROX paste here.
    static func looksLikeResultURL(_ raw: String) -> Bool {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let comps = URLComponents(string: trimmed),
              comps.scheme?.lowercased() == "https",
              let host = comps.host?.lowercased()
        else { return false }
        return host == resultsHost
    }
}

/// Athlete-readable failure for the import flow. Maps the server's `error.code`
/// (and transport failures) to a single honest Spanish message so the sheet
/// never shows a raw status code or a misleading "try again" on a bad link.
enum CarrerasImportError: Error {
    case invalidLink
    case unauthorized
    case hyroxUnreachable
    case unreadable
    case generic

    /// Build from the wire `APIError`. The import route returns
    /// `{ error: { code, message } }`; we key off the stable `code` (400 →
    /// invalid_url/invalid_host, 401 → unauthorized, 422 → fetch/parse, else
    /// generic) rather than the localized message.
    init(apiError: APIError) {
        switch apiError {
        case .offline:
            self = .hyroxUnreachable
        case .invalidResponse, .decoding:
            self = .generic
        case let .http(status, data):
            let code = Self.errorCode(from: data)
            switch (status, code) {
            case (401, _):
                self = .unauthorized
            case (_, "invalid_url"), (_, "invalid_host"), (400, _):
                self = .invalidLink
            case (_, "fetch_failed"):
                self = .hyroxUnreachable
            case (422, _), (_, "store_failed"):
                self = .unreadable
            default:
                self = .generic
            }
        }
    }

    /// The message shown to the athlete in the sheet.
    var message: String {
        switch self {
        case .invalidLink:
            return "Ese enlace no es una página de resultado de HYROX. Copia el enlace de tu página de atleta en \(HyroxImport.resultsHost)."
        case .unauthorized:
            return "Tu sesión ha caducado. Vuelve a iniciar sesión e inténtalo de nuevo."
        case .hyroxUnreachable:
            return "No pudimos conectar con HYROX. Revisa tu conexión e inténtalo de nuevo en un momento."
        case .unreadable:
            return "No pudimos leer ese resultado. Asegúrate de pegar el enlace de tu página de atleta, no el del listado general."
        case .generic:
            return "No se pudo importar el resultado. Inténtalo de nuevo."
        }
    }

    /// Best-effort extraction of `error.code` from a JSON error body. Failure to
    /// parse degrades to nil → the caller falls back on the HTTP status.
    private static func errorCode(from data: Data) -> String? {
        struct Envelope: Decodable { struct Inner: Decodable { let code: String? }; let error: Inner? }
        return (try? JSONDecoder().decode(Envelope.self, from: data))?.error?.code
    }
}

// MARK: - Station detail (deep-dive contract)

/// One sub-metric tile in a station detail (best / avg / sled weight / stops).
struct StationSubMetric: Codable, Identifiable, Hashable {
    let id: String
    let label: String
    let value: String?
    let unit: String?
    /// Optional semantic emphasis: "neutral" | "warning" | "danger" | "ok".
    let emphasis: String?
}

/// One bar in a between-races trend (a station time per past race).
struct StationTrendPoint: Codable, Identifiable, Hashable {
    let id: String
    /// Short race label under the bar, e.g. "nov".
    let label: String
    /// Normalized bar height 0…1 (taller = slower, per the handoff).
    let height: Double
    /// Pre-formatted time for the bar's caption, e.g. "2:48".
    let time: String?
    /// "better" | "slightly_worse" | "worse" — colors the most-recent bar.
    let severity: String
}

/// A training-link row: a session/group that works this station or running.
struct TrainingLink: Codable, Identifiable, Hashable {
    let id: String
    /// Session/block name, e.g. "Fuerza base · piernas".
    let title: String
    /// Group + descriptor, e.g. "G01 · sentadilla, empuje".
    let group: String?
    /// Times trained, pre-formatted, e.g. "×8". Nil for the "next" row.
    let count: String?
    /// When set, this is the highlighted "→ next" row (e.g. "hoy PM").
    let next_label: String?
    /// Modality string for the leading dot color (run/erg/strength).
    let modality: String?

    // The APIClient decoder uses `.convertFromSnakeCase`, which rewrites the wire
    // key `next_label` to `nextLabel` BEFORE matching — so a property literally
    // named `next_label` would never match. Map the multi-word key to the
    // post-conversion form so it decodes while the property name (referenced by
    // the views) stays snake_case. Single-word keys match as-is.
    enum CodingKeys: String, CodingKey {
        case id
        case title
        case group
        case count
        case next_label = "nextLabel"
        case modality
    }
}

/// Per-station deep-dive bundle.
///
/// Backs `GET /api/athlete/stations/{station}` (LIVE) — built from the athlete's
/// imported HYROX splits; honest-empty when no race recorded this station.
struct StationDetail: Codable, Identifiable, Hashable {
    /// Station name (matches the catalogue label).
    let id: String
    let station: String
    /// Technique video URL — nil keeps the honest placeholder.
    let technique_video_url: String?
    /// Athlete's last time + benchmark + delta + percentile for the hero card.
    let last_time: String?
    let benchmark_time: String?
    let delta: String?
    /// Signed-delta severity: "better" | "slightly_worse" | "worse".
    let severity: String
    /// Bar fraction 0…1 for the hero comparison bar.
    let fraction: Double
    /// Percentile banner, e.g. "top 42%".
    let percentile_label: String?
    let trend: [StationTrendPoint]
    let sub_metrics: [StationSubMetric]
    let training: [TrainingLink]
    /// IA recommendation prose + optional bold objective ("sub 2:20").
    let ia_recommendation: String?
    let ia_objective: String?

    // `.convertFromSnakeCase` rewrites each multi-word wire key to camelCase
    // before matching; map each so the detail decodes while the views keep their
    // snake_case property references. Single-word keys (station, severity,
    // fraction, trend, training) match as-is.
    enum CodingKeys: String, CodingKey {
        case id
        case station
        case technique_video_url = "techniqueVideoUrl"
        case last_time = "lastTime"
        case benchmark_time = "benchmarkTime"
        case delta
        case severity
        case fraction
        case percentile_label = "percentileLabel"
        case trend
        case sub_metrics = "subMetrics"
        case training
        case ia_recommendation = "iaRecommendation"
        case ia_objective = "iaObjective"
    }
}

// MARK: - Running deep-dive (analysis contract)

/// One row in the running pace-zone table (Z2–Z5).
struct RunningPaceZone: Codable, Identifiable, Hashable {
    let id: String
    /// Zone index 2…5 → drives the zone dot color.
    let zone: Int
    /// Zone descriptor, e.g. "rodaje" / "umbral".
    let descriptor: String
    /// Pace or range, pre-formatted, e.g. "5:10–5:30" / "4:05".
    let pace: String?
    /// True for the threshold zone, which the handoff accents.
    let highlight: Bool
}

/// One bar in the threshold-progression chart (a pace per past block).
struct RunningProgressionPoint: Codable, Identifiable, Hashable {
    let id: String
    /// Normalized bar height 0…1 (taller = slower, per the handoff).
    let height: Double
    /// Pre-formatted pace caption, e.g. "4:20".
    let pace: String?
    /// True for the most-recent (best) bar, which the handoff accents.
    let current: Bool
}

/// Running deep-dive bundle (running-derived analytics).
///
/// Backs `GET /api/athlete/running-analysis` (live). Fields the system can't
/// measure yet come back null / empty (e.g. threshold/VO₂/zones when there's no
/// 5K benchmark, training links) so the view keeps honest empty states.
struct RunningAnalysis: Codable, Hashable {
    /// Key-metric tiles (pre-formatted strings keep the wire/display simple).
    let threshold_pace: String?
    /// The Jack-Daniels VDOT off the latest 5 km (e.g. "49.9") — despite the
    /// wire name, this carries the VDOT number, surfaced as "VDOT 49,9".
    let vo2_estimate: String?
    let best_1k: String?
    /// Weekly running volume — el volumen de la semana ISO tal como lo trae el
    /// propio análisis de carrera.
    let weekly_volume_km: String?
    /// Rolling last-7-days running volume — the Inicio "Volumen · 7 días" figure
    /// (distinct from `weekly_volume_km`, which is the ISO week). Nil when none.
    let volume_7d_km: String?
    /// run_5k benchmark history (oldest→newest) — the Inicio 5 km trend. Empty
    /// when the athlete has no 5 km test on file.
    @LossyArray var five_k_trend: [FiveKTrendPoint]   // AUDIT-B3 — drop a bad row, not the analysis
    /// The most recent race's 8×1 km splits (per-km pace bars).
    @LossyArray var splits: [RunningSplit]
    /// Optional final-pace-drop callout, e.g. "+18s/km final".
    let split_drop_note: String?
    @LossyArray var pace_zones: [RunningPaceZone]
    @LossyArray var progression: [RunningProgressionPoint]
    @LossyArray var training: [TrainingLink]

    // The APIClient decoder uses `.convertFromSnakeCase`, which rewrites each
    // wire key to camelCase BEFORE matching the CodingKey. Multi-word snake_case
    // properties (threshold_pace, best_1k, …) would therefore never match. Map
    // each to the post-conversion form so the payload decodes while the property
    // names the views reference stay snake_case. Note `best_1k` converts to
    // `best1k` (digit folded into the prior segment), not `best_1K`; likewise
    // `five_k_trend` → `fiveKTrend` and `volume_7d_km` → `volume7dKm`.
    enum CodingKeys: String, CodingKey {
        case threshold_pace = "thresholdPace"
        case vo2_estimate = "vo2Estimate"
        case best_1k = "best1k"
        case weekly_volume_km = "weeklyVolumeKm"
        case volume_7d_km = "volume7dKm"
        case five_k_trend = "fiveKTrend"
        case splits
        case split_drop_note = "splitDropNote"
        case pace_zones = "paceZones"
        case progression
        case training
    }
}

/// One past 5 km time trial — the run_5k benchmark history. Single-word wire
/// fields (`date` / `seconds` / `time`) need no snake_case mapping, so they
/// decode cleanly under the convertFromSnakeCase decoder AND round-trip verbatim
/// through the plain on-disk coder.
struct FiveKTrendPoint: Codable, Hashable, Identifiable {
    var id: String { date }
    let date: String      // YYYY-MM-DD the test was recorded
    let seconds: Int      // total 5 km time (drives the sparkline + delta)
    let time: String      // pre-formatted "m:ss" (e.g. "19:58")
}
