import Foundation

// Service + Codable models for the Carreras (performance/race) hub: race
// results, the IA weakness report, station benchmarks, and running splits.
//
// LIVE: the race-derived endpoints now ship. fetchOverview hits
// `GET /api/athlete/race-context`, fetchStationDetail hits
// `GET /api/athlete/stations/{station}`, fetchRunningAnalysis hits
// `GET /api/athlete/running-analysis`, and importRace POSTs an official HYROX
// detail link to `POST /api/athlete/race-results/import`. Each read degrades to
// nil on no-bearer / request failure (so the views render honest empty states),
// and each endpoint is itself honest-empty when the athlete has no imported race.
//
// What is ALSO live: the training analytics from `GET /api/athlete/analytics`
// (StatsService / AthleteAnalytics). Carreras' "Rendimiento" section surfaces
// those real numbers — see StatsService.fetchAnalytics; this file does NOT
// re-fetch them, it only owns the race-derived contract.
//
// Snake_case Codable keys match the project convention (Swift Codable mirrors
// the API's snake_case responses).

// MARK: - Models

/// A completed race result with split breakdown.
struct RaceResultSummary: Codable, Identifiable, Hashable {
    let id: String
    let event_name: String
    /// ISO date (YYYY-MM-DD) of the race.
    let date: String
    /// Division / category label, e.g. "Pro", "Open".
    let division: String?
    /// Total time, pre-formatted "H:MM:SS".
    let total_time: String?
    /// Split times (pre-formatted) for the headline tiles.
    let run_time: String?
    let stations_time: String?
    let roxzone_time: String?
    /// Percentile / ranking banner, e.g. "Top 18% de tu división".
    let standing_label: String?
    /// Delta vs the athlete's previous race, pre-formatted "−2:34".
    let delta_vs_previous: String?
    /// Total time in whole seconds — drives the evolution chart's relative bar
    /// heights without re-parsing the formatted `total_time`. Nil when unknown.
    let total_seconds: Int?

    // APIClient decodes with `.convertFromSnakeCase`, which rewrites each wire key
    // to camelCase BEFORE matching the CodingKey. The default CodingKey for a
    // snake_case property keeps the snake_case string, so a multi-word property
    // (event_name, total_time, …) would never match and a NON-optional one
    // (event_name) would throw and take the whole overview decode down. Map each
    // to the post-conversion form so the payload decodes while the property names
    // the views reference stay snake_case. Single-word keys match as-is.
    enum CodingKeys: String, CodingKey {
        case id
        case event_name = "eventName"
        case date
        case division
        case total_time = "totalTime"
        case run_time = "runTime"
        case stations_time = "stationsTime"
        case roxzone_time = "roxzoneTime"
        case standing_label = "standingLabel"
        case delta_vs_previous = "deltaVsPrevious"
        case total_seconds = "totalSeconds"
    }
}

/// The IA weakness report attached to a race.
struct RaceIAReport: Codable, Hashable {
    /// Free-ish prose of what to prioritize (generated by the methodology IA).
    let summary: String
    /// Recommended training-group chips, e.g. ["G03 · Ergómetros", …].
    let recommended_groups: [String]

    // `.convertFromSnakeCase` rewrites `recommended_groups` → `recommendedGroups`
    // before matching, so map the multi-word key to the post-conversion form.
    enum CodingKeys: String, CodingKey {
        case summary
        case recommended_groups = "recommendedGroups"
    }
}

/// A station benchmark comparison row (athlete vs division benchmark).
struct StationBenchmark: Codable, Identifiable, Hashable {
    let id: String
    /// Station name, e.g. "Sled Push".
    let station: String
    /// Athlete's time for the station, pre-formatted.
    let time: String?
    /// Signed delta vs benchmark, pre-formatted "+0:42" / "−0:08".
    let delta: String?
    /// Normalized bar fraction 0…1 for the comparison bar.
    let fraction: Double
    /// Sign of the delta: "better" | "slightly_worse" | "worse".
    let severity: String
}

/// Per-km running split for the pace chart.
struct RunningSplit: Codable, Identifiable, Hashable {
    let id: String
    /// Km index label, e.g. "k1".
    let label: String
    /// Pace time for the km, pre-formatted "3:45".
    let pace: String?
    /// Normalized bar height 0…1.
    let height: Double
    /// "better" | "slightly_worse" | "worse".
    let severity: String
}

/// The bundle the Carreras hub loads in one shot.
struct CarrerasOverview: Codable, Hashable {
    let last_race: RaceResultSummary?
    let ia_report: RaceIAReport?
    let station_benchmarks: [StationBenchmark]
    let running_splits: [RunningSplit]
    /// Optional final-pace-drop callout for the per-km chart, e.g.
    /// "Caída de ritmo en los últimos 2 km (+18s/km)".
    let pace_drop_note: String?
    /// History of prior races (most recent first), for the list at the bottom.
    let history: [RaceResultSummary]

    // `.convertFromSnakeCase` rewrites each multi-word wire key (last_race →
    // lastRace, …) before matching; the snake_case property's default CodingKey
    // would never match. Map each to the post-conversion form so the bundle
    // decodes while the views keep referencing snake_case properties.
    enum CodingKeys: String, CodingKey {
        case last_race = "lastRace"
        case ia_report = "iaReport"
        case station_benchmarks = "stationBenchmarks"
        case running_splits = "runningSplits"
        case pace_drop_note = "paceDropNote"
        case history
    }
}

// MARK: - Severity mapping
//
// The wire layer speaks `"better" | "slightly_worse" | "worse"`; the views need
// `BenchmarkBarRow.Severity`. One conversion, single-sourced here so every
// surface (benchmark rows, pace bars) agrees and an unknown string degrades to
// the neutral-worst reading rather than crashing.

extension BenchmarkBarRow.Severity {
    init(wire raw: String) {
        switch raw.lowercased() {
        case "better":         self = .better
        case "slightly_worse": self = .slightlyWorse
        default:               self = .worse
        }
    }
}

// MARK: - Station catalogue
//
// The 8 non-run HYROX stations the deep-dive is replicable across, derived from
// the canonical RaceModels station labels (the even indices — odd indices are
// the eight 1 km runs). Single source so the hub grid, the detail screen and
// any future per-station routing share one ordered list and never drift.

enum CarrerasStations {
    /// The eight HYROX work stations, in race order.
    static let all: [String] = HyroxStation.labels
        .filter { !HyroxStation.runIndices.contains($0.key) }
        .sorted { $0.key < $1.key }
        .map { $0.value }
}

// MARK: - Service

enum CarrerasService {
    /// Load the Carreras hub overview for the authenticated athlete.
    ///
    /// LIVE: `GET /api/athlete/race-context` builds the bundle from the athlete's
    /// IMPORTED HYROX results — last race summary, per-station benchmarks, the
    /// 8×1 km running splits, an optional pace-drop note, and the race history.
    /// The endpoint is honest-empty (every field null/empty) when the athlete has
    /// no imported race yet, so the hub still renders its "aún no hay carreras"
    /// empty state. Returns nil only when there's no bearer or the request fails
    /// (so the view degrades to its empty state rather than erroring).
    static func fetchOverview(bearer: String?) async -> CarrerasOverview? {
        guard let bearer else { return nil }
        do {
            return try await APIClient.shared.get(
                path: "api/athlete/race-context",
                bearer: bearer
            )
        } catch {
            return nil
        }
    }

    /// Import an official HYROX result for the authenticated athlete.
    ///
    /// `POST /api/athlete/race-results/import` with `{ result_url }`. The server
    /// fetches + parses the HYROX detail page and upserts the athlete's `races`
    /// row (idempotent per HYROX idp — re-pasting refreshes). On success the hub
    /// should re-fetch `fetchOverview` to surface the new race.
    ///
    /// Throws `CarrerasImportError` with an athlete-readable message keyed off the
    /// server's error code, or a network/decoding wrapper, so the sheet can show
    /// an honest reason rather than a generic failure.
    static func importRace(resultURL: String, bearer: String?) async throws {
        guard let bearer else { throw CarrerasImportError.unauthorized }
        do {
            // We don't need the parsed result on-device; a successful 201 is the
            // signal to refresh. Decode into Empty so an unexpected body shape
            // can never fail the import after the server already stored it.
            let _: Empty = try await APIClient.shared.post(
                path: "api/athlete/race-results/import",
                body: HyroxImportBody(result_url: resultURL),
                bearer: bearer
            )
        } catch let error as APIError {
            throw CarrerasImportError(apiError: error)
        } catch is CancellationError {
            throw CancellationError()
        } catch {
            // `session.data(for:)` surfaces transport failures (offline, timeout,
            // DNS) as URLError BEFORE APIClient wraps them — treat those as a
            // reachability problem, not a bad link.
            throw CarrerasImportError.hyroxUnreachable
        }
    }

    /// Detail for a single station across the athlete's races.
    ///
    /// LIVE: `GET /api/athlete/stations/{station}` computes the deep-dive from the
    /// athlete's imported HYROX results — last time vs their own best (+ delta,
    /// severity, percentile from station rank / field size), the trend across
    /// imported races, sub-metrics, the methodology groups that train it, and the
    /// technique video when seeded. IA recommendation is deferred (null). The
    /// `{station}` segment is the station LABEL (percent-encoded path segment);
    /// the backend resolves it tolerantly to the canonical HYROX station. Returns
    /// nil on no bearer or request failure so the view renders its empty state;
    /// an empty (but non-nil) detail is returned when there are simply no races.
    static func fetchStationDetail(station: String, bearer: String?) async -> StationDetail? {
        guard let bearer else { return nil }
        let encoded = station.addingPercentEncoding(
            withAllowedCharacters: .urlPathAllowed
        ) ?? station
        do {
            return try await APIClient.shared.get(
                path: "api/athlete/stations/\(encoded)",
                bearer: bearer
            )
        } catch {
            return nil
        }
    }

    /// Running deep-dive metrics (threshold pace, VO₂ est., best 1 km, pace
    /// zones, threshold progression, the training that works it).
    ///
    /// LIVE: `GET /api/athlete/running-analysis` computes the bundle from the
    /// athlete's stored run segments + a Jack-Daniels VDOT off their 5K
    /// benchmark. Fields the system can't measure yet (threshold/VO₂/zones with
    /// no 5K, training links) come back null / empty and the view renders honest
    /// empty states. Returns nil only when there's no bearer or the request
    /// fails, so the screen degrades to its empty state rather than erroring.
    static func fetchRunningAnalysis(bearer: String?) async -> RunningAnalysis? {
        guard let bearer else { return nil }
        do {
            return try await APIClient.shared.get(
                path: "api/athlete/running-analysis",
                bearer: bearer
            )
        } catch {
            return nil
        }
    }
}

// MARK: - Import request + errors

/// Request body for `POST /api/athlete/race-results/import`. The encoder applies
/// `.convertToSnakeCase`; an all-lowercase `result_url` has no case boundary so
/// it is emitted verbatim, matching the server's `hyroxImportInput` Zod schema.
private struct HyroxImportBody: Encodable {
    let result_url: String
}

/// HYROX detail-page host the athlete must paste from. Single source for the
/// client-side pre-flight check + the empty-state copy; the server re-validates
/// this exact host (SSRF allowlist) so it is authoritative — this constant only
/// gives the athlete instant feedback for the obvious wrong-link case.
enum HyroxImport {
    static let resultsHost = "results.hyrox.com"

    /// Lightweight client-side check that a pasted string LOOKS like a HYROX
    /// results detail link: an https URL whose host is exactly results.hyrox.com.
    /// Deliberately permissive about the query (season/idp/event are validated
    /// server-side) — we only catch the clearly-not-HYROX paste here.
    static func looksLikeResultURL(_ raw: String) -> Bool {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let comps = URLComponents(string: trimmed),
              comps.scheme?.lowercased() == "https",
              let host = comps.host?.lowercased()
        else { return false }
        return host == resultsHost
    }
}

/// Athlete-readable failure for the import flow. Maps the server's `error.code`
/// (and transport failures) to a single honest Spanish message so the sheet
/// never shows a raw status code or a misleading "try again" on a bad link.
enum CarrerasImportError: Error {
    case invalidLink
    case unauthorized
    case hyroxUnreachable
    case unreadable
    case generic

    /// Build from the wire `APIError`. The import route returns
    /// `{ error: { code, message } }`; we key off the stable `code` (400 →
    /// invalid_url/invalid_host, 401 → unauthorized, 422 → fetch/parse, else
    /// generic) rather than the localized message.
    init(apiError: APIError) {
        switch apiError {
        case .offline:
            self = .hyroxUnreachable
        case .invalidResponse, .decoding:
            self = .generic
        case let .http(status, data):
            let code = Self.errorCode(from: data)
            switch (status, code) {
            case (401, _):
                self = .unauthorized
            case (_, "invalid_url"), (_, "invalid_host"), (400, _):
                self = .invalidLink
            case (_, "fetch_failed"):
                self = .hyroxUnreachable
            case (422, _), (_, "store_failed"):
                self = .unreadable
            default:
                self = .generic
            }
        }
    }

    /// The message shown to the athlete in the sheet.
    var message: String {
        switch self {
        case .invalidLink:
            return "Ese enlace no es una página de resultado de HYROX. Copia el enlace de tu página de atleta en \(HyroxImport.resultsHost)."
        case .unauthorized:
            return "Tu sesión ha caducado. Vuelve a iniciar sesión e inténtalo de nuevo."
        case .hyroxUnreachable:
            return "No pudimos conectar con HYROX. Revisa tu conexión e inténtalo de nuevo en un momento."
        case .unreadable:
            return "No pudimos leer ese resultado. Asegúrate de pegar el enlace de tu página de atleta, no el del listado general."
        case .generic:
            return "No se pudo importar el resultado. Inténtalo de nuevo."
        }
    }

    /// Best-effort extraction of `error.code` from a JSON error body. Failure to
    /// parse degrades to nil → the caller falls back on the HTTP status.
    private static func errorCode(from data: Data) -> String? {
        struct Envelope: Decodable { struct Inner: Decodable { let code: String? }; let error: Inner? }
        return (try? JSONDecoder().decode(Envelope.self, from: data))?.error?.code
    }
}

// MARK: - Station detail (deep-dive contract)

/// One sub-metric tile in a station detail (best / avg / sled weight / stops).
struct StationSubMetric: Codable, Identifiable, Hashable {
    let id: String
    let label: String
    let value: String?
    let unit: String?
    /// Optional semantic emphasis: "neutral" | "warning" | "danger" | "ok".
    let emphasis: String?
}

/// One bar in a between-races trend (a station time per past race).
struct StationTrendPoint: Codable, Identifiable, Hashable {
    let id: String
    /// Short race label under the bar, e.g. "nov".
    let label: String
    /// Normalized bar height 0…1 (taller = slower, per the handoff).
    let height: Double
    /// Pre-formatted time for the bar's caption, e.g. "2:48".
    let time: String?
    /// "better" | "slightly_worse" | "worse" — colors the most-recent bar.
    let severity: String
}

/// A training-link row: a session/group that works this station or running.
struct TrainingLink: Codable, Identifiable, Hashable {
    let id: String
    /// Session/block name, e.g. "Fuerza base · piernas".
    let title: String
    /// Group + descriptor, e.g. "G01 · sentadilla, empuje".
    let group: String?
    /// Times trained, pre-formatted, e.g. "×8". Nil for the "next" row.
    let count: String?
    /// When set, this is the highlighted "→ next" row (e.g. "hoy PM").
    let next_label: String?
    /// Modality string for the leading dot color (run/erg/strength).
    let modality: String?

    // The APIClient decoder uses `.convertFromSnakeCase`, which rewrites the wire
    // key `next_label` to `nextLabel` BEFORE matching — so a property literally
    // named `next_label` would never match. Map the multi-word key to the
    // post-conversion form so it decodes while the property name (referenced by
    // the views) stays snake_case. Single-word keys match as-is.
    enum CodingKeys: String, CodingKey {
        case id
        case title
        case group
        case count
        case next_label = "nextLabel"
        case modality
    }
}

/// Per-station deep-dive bundle.
///
/// BACKEND GAP: backs `GET /api/athlete/stations/{station}`.
struct StationDetail: Codable, Identifiable, Hashable {
    /// Station name (matches the catalogue label).
    let id: String
    let station: String
    /// Technique video URL — nil keeps the honest placeholder.
    let technique_video_url: String?
    /// Athlete's last time + benchmark + delta + percentile for the hero card.
    let last_time: String?
    let benchmark_time: String?
    let delta: String?
    /// Signed-delta severity: "better" | "slightly_worse" | "worse".
    let severity: String
    /// Bar fraction 0…1 for the hero comparison bar.
    let fraction: Double
    /// Percentile banner, e.g. "top 42%".
    let percentile_label: String?
    let trend: [StationTrendPoint]
    let sub_metrics: [StationSubMetric]
    let training: [TrainingLink]
    /// IA recommendation prose + optional bold objective ("sub 2:20").
    let ia_recommendation: String?
    let ia_objective: String?

    // `.convertFromSnakeCase` rewrites each multi-word wire key to camelCase
    // before matching; map each so the detail decodes while the views keep their
    // snake_case property references. Single-word keys (station, severity,
    // fraction, trend, training) match as-is.
    enum CodingKeys: String, CodingKey {
        case id
        case station
        case technique_video_url = "techniqueVideoUrl"
        case last_time = "lastTime"
        case benchmark_time = "benchmarkTime"
        case delta
        case severity
        case fraction
        case percentile_label = "percentileLabel"
        case trend
        case sub_metrics = "subMetrics"
        case training
        case ia_recommendation = "iaRecommendation"
        case ia_objective = "iaObjective"
    }
}

// MARK: - Running deep-dive (analysis contract)

/// One row in the running pace-zone table (Z2–Z5).
struct RunningPaceZone: Codable, Identifiable, Hashable {
    let id: String
    /// Zone index 2…5 → drives the zone dot color.
    let zone: Int
    /// Zone descriptor, e.g. "rodaje" / "umbral".
    let descriptor: String
    /// Pace or range, pre-formatted, e.g. "5:10–5:30" / "4:05".
    let pace: String?
    /// True for the threshold zone, which the handoff accents.
    let highlight: Bool
}

/// One bar in the threshold-progression chart (a pace per past block).
struct RunningProgressionPoint: Codable, Identifiable, Hashable {
    let id: String
    /// Normalized bar height 0…1 (taller = slower, per the handoff).
    let height: Double
    /// Pre-formatted pace caption, e.g. "4:20".
    let pace: String?
    /// True for the most-recent (best) bar, which the handoff accents.
    let current: Bool
}

/// Running deep-dive bundle (running-derived analytics).
///
/// Backs `GET /api/athlete/running-analysis` (live). Fields the system can't
/// measure yet come back null / empty (e.g. threshold/VO₂/zones when there's no
/// 5K benchmark, training links) so the view keeps honest empty states.
struct RunningAnalysis: Codable, Hashable {
    /// Key-metric tiles (pre-formatted strings keep the wire/display simple).
    let threshold_pace: String?
    let vo2_estimate: String?
    let best_1k: String?
    /// Weekly running volume — present in the analysis payload, but ALSO live
    /// via StatsService; the deep-dive prefers the live StatsService figure and
    /// treats this as a fallback so the two never silently disagree.
    let weekly_volume_km: String?
    /// The most recent race's 8×1 km splits (per-km pace bars).
    let splits: [RunningSplit]
    /// Optional final-pace-drop callout, e.g. "+18s/km final".
    let split_drop_note: String?
    let pace_zones: [RunningPaceZone]
    let progression: [RunningProgressionPoint]
    let training: [TrainingLink]

    // The APIClient decoder uses `.convertFromSnakeCase`, which rewrites each
    // wire key to camelCase BEFORE matching the CodingKey. Multi-word snake_case
    // properties (threshold_pace, best_1k, …) would therefore never match. Map
    // each to the post-conversion form so the payload decodes while the property
    // names the views reference stay snake_case. Note `best_1k` converts to
    // `best1k` (digit folded into the prior segment), not `best_1K`.
    enum CodingKeys: String, CodingKey {
        case threshold_pace = "thresholdPace"
        case vo2_estimate = "vo2Estimate"
        case best_1k = "best1k"
        case weekly_volume_km = "weeklyVolumeKm"
        case splits
        case split_drop_note = "splitDropNote"
        case pace_zones = "paceZones"
        case progression
        case training
    }
}
