// Thin re-export shim. Single source of truth lives in
// `@fahybrid/shared/schema/coach-weekly-review`. The legacy local convention
// suffixes status enum constants with `Schema`; aliased below for parity.

export {
  coachWeeklyReviewStatus as coachWeeklyReviewStatusSchema,
  cohortPolarizationSchema,
  weeklyReviewSnapshotSchema,
  weeklyAttentionItemSchema,
  weeklyTransitionItemSchema,
  massAdjustmentKindSchema,
  massAdjustmentOpportunitySchema,
  cohortPlanDaySchema,
  cohortPlanWeekSchema,
  weeklyReviewDecisionSchema,
  weeklyReviewNoteSchema,
  weeklyReviewPlanEditSchema,
  coachWeeklyReviewSchema,
  saveWeeklyReviewRequestSchema,
  weeklyReviewHistoryItemSchema,
  type CoachWeeklyReviewStatus,
  type CohortPolarization,
  type WeeklyReviewSnapshot,
  type WeeklyAttentionItem,
  type WeeklyTransitionItem,
  type MassAdjustmentKind,
  type MassAdjustmentOpportunity,
  type CohortPlanDay,
  type CohortPlanWeek,
  type WeeklyReviewDecision,
  type WeeklyReviewNote,
  type WeeklyReviewPlanEdit,
  type CoachWeeklyReview,
  type SaveWeeklyReviewRequest,
  type WeeklyReviewHistoryItem,
} from '@fahybrid/shared/schema/coach-weekly-review';
