-- 0096_google_oauth_tokens.sql
--
-- One-shot Google OAuth refresh_token store for the citas videollamada adapter
-- (funnel task #26). A single coach connects a Google account (hello@fahybrid.com)
-- ONCE via /api/citas/google/connect; the callback captures the offline
-- refresh_token and upserts it here. `provider` is unique → exactly one 'google'
-- row. lib/citas/google.ts mints short-lived access tokens from this refresh_token
-- to create Calendar events + Meet links; access tokens are NEVER persisted.
--
-- Also adds appointments.google_event_id so an accepted cita's Calendar event can be
-- deleted when the cita is cancelled (cancel-hook — see TODO(#26) in lib/citas/meeting.ts).
--
-- Additive + idempotent (`if not exists` everywhere). The runner wraps the file in a
-- single transaction; no begin/commit here.

create table if not exists google_oauth_tokens (
  id            bigserial primary key,
  provider      text not null unique,               -- 'google' (single row; unique upsert target)
  refresh_token text not null,                       -- long-lived offline token (access_type=offline)
  updated_at    timestamptz not null default now(),
  created_at    timestamptz not null default now()
);

comment on table google_oauth_tokens is
  'One-shot OAuth refresh_token store per provider (currently only google) for the citas Calendar/Meet adapter. Upserted on the provider unique constraint; access tokens are minted on demand, never stored.';

-- google_event_id lets the cancel path delete the created Calendar event (best-effort).
alter table appointments add column if not exists google_event_id text;

comment on column appointments.google_event_id is
  'Google Calendar event id for the auto-created videollamada (set when the Meet link is generated by the adapter). Used to delete the event if the cita is cancelled.';
