-- 0284 — Fichas de fuerza, habilidad, pliometría, cardio y estaciones para lanzamiento.
-- Fuente: docs/auditoria-biblioteca-ejercicios-2026-10-01.json (91 filas globales activas).
-- Texto original en español: explica el gesto, sin fijar dosis ni método del coach.
-- Las estaciones HYROX no congelan pesos, sexo, distancia ni repeticiones de un evento.
-- Farmers permite depositar las cargas para descansar sin avanzar (reglamento 26/27, §8.6).
-- No se modifican IDs, nombres, alias, modalidad, overrides, vídeos ni filas privadas/archivadas.
-- Métricas: flags canónicos solo para fichas vacías; 0286 normaliza las históricas.

update exercises as e
set description = v.description,
    cues = v.cues,
    default_metrics_json = case when e.default_metrics_json = '{}'::jsonb
      then v.metrics else e.default_metrics_json end,
    updated_at = now()
from (values
  ('band-pull-apart',
   'Apertura de los brazos contra la resistencia de una banda, manteniendo los codos extendidos y el tronco estable.',
   'Sujeta la banda delante del pecho y abre las manos sin elevar los hombros. Mantén las costillas recogidas y vuelve de forma controlada, sin dejar que la banda tire de los brazos.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('diagonal-band-pull-apart',
   'Apertura de una banda siguiendo una diagonal, con una mano arriba y la otra abajo.',
   'Tensa la banda suavemente antes de abrir los brazos. Mueve los hombros sin girar el tronco ni arquear la espalda; cambia la diagonal según la variante indicada.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('cable-fly',
   'Aproximación de los brazos por delante del pecho contra la resistencia de las poleas.',
   'Mantén una pequeña flexión de los codos y el pecho estable. Acerca las manos siguiendo un arco sin convertir el gesto en un press; vuelve hasta un recorrido cómodo para los hombros.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('snatch',
   'Elevación de una barra desde el suelo hasta una posición estable sobre la cabeza en un movimiento continuo.',
   'Mantén la barra cerca del cuerpo al extender piernas y cadera. Colócate debajo para recibirla con los brazos extendidos; estabiliza el apoyo antes de incorporarte o bajar la barra.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('dumbbell-snatch',
   'Elevación de una mancuerna con un brazo desde abajo hasta una posición estable sobre la cabeza.',
   'Impulsa la carga con piernas y cadera, manteniéndola cerca del cuerpo. Recíbela sobre el hombro con el codo extendido y el tronco estable; controla el descenso y el cambio de mano indicado.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('hyrox-sled-pull',
   'Arrastre de un trineo mediante una cuerda, acercándolo hacia el cuerpo con tracciones sucesivas.',
   'Apoya los pies con firmeza y mantén tensión en el tronco. Tira de la cuerda sin dar tirones bruscos con la espalda y recoge la cuerda para que no se enrede con los pies. Carga y recorrido los fija la prescripción.', '{"reps":true,"time":true,"rpe":true,"distance":true,"weight":true}'::jsonb),
  ('sled-drag-backwards',
   'Desplazamiento hacia atrás arrastrando un trineo con una conexión firme a la carga.',
   'Comprueba el recorrido antes de empezar. Mantén tensión en la conexión y da pasos hacia atrás con apoyo estable, sin cruzar los pies ni dejar que la espalda absorba los tirones.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('assault-bike',
   'Pedaleo en bicicleta de aire coordinado con el empuje y la tracción de los brazos.',
   'Ajusta el sillín para pedalear sin balancear la pelvis. Mantén los pies apoyados y acompaña el pedaleo con ambos brazos, sin encoger los hombros ni cerrar las rodillas hacia dentro.', '{"time":true,"distance":true,"rpe":true,"hr":true,"calories":true}'::jsonb),
  ('atlas-stone-shoulder',
   'Elevación de una piedra de entrenamiento desde el suelo hasta un hombro, pasando por un apoyo intermedio sobre los muslos.',
   'Acerca la piedra al cuerpo y rodea la carga con los brazos. Usa piernas y cadera para llevarla al hombro, estabiliza el apoyo y controla la bajada en una zona preparada para ese material.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('bike-erg',
   'Pedaleo en un ergómetro de bicicleta, con el trabajo medido por tiempo, distancia o energía.',
   'Ajusta el sillín y apoya bien los pies. Pedalea con una cadencia uniforme y el tronco estable; usa la pantalla para seguir el objetivo indicado sin balancear la pelvis.', '{"time":true,"distance":true,"rpe":true,"hr":true,"calories":true}'::jsonb),
  ('good-morning',
   'Bisagra de cadera con el tronco inclinado hacia delante y una carga o resistencia colocada según la variante.',
   'Desbloquea ligeramente las rodillas y lleva la cadera hacia atrás. Mantén la carga cerca de su apoyo y el tronco firme; termina el recorrido antes de perder la posición de la espalda.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('burpee',
   'Movimiento que combina bajar las manos al suelo, llevar los pies atrás y volver a una posición de pie, con el final indicado por el coach.',
   'Apoya las manos con estabilidad y controla el tronco al llevar los pies atrás. Regresa con los pies bien apoyados antes de incorporarte; sigue la variante prescrita para el contacto del pecho y el salto final.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('w9-burpee-to-plate',
   'Burpee seguido de un salto para apoyar los pies sobre un disco situado delante del cuerpo.',
   'Coloca el disco plano y comprueba que no resbala. Completa el burpee, recoge los pies y aterriza sobre el disco con equilibrio; baja de forma controlada para reiniciar.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('hyrox-burpee-broad-jump',
   'Secuencia de burpee y salto hacia delante, encadenada para avanzar por un recorrido.',
   'Controla el descenso hasta el suelo y coloca las manos sin invadir el apoyo de los pies. Tras incorporarte, impulsa el salto hacia delante y aterriza de forma estable antes del siguiente burpee. Sigue el estándar indicado para la sesión.', '{"reps":true,"time":true,"rpe":true,"distance":true}'::jsonb),
  ('walk',
   'Desplazamiento a pie a un ritmo indicado por el coach, en exterior o sobre una cinta.',
   'Camina con pasos naturales y una postura erguida, dejando que los brazos acompañen el movimiento. Adapta el apoyo al terreno y sigue el objetivo de tiempo, distancia o esfuerzo de la sesión.', '{"time":true,"distance":true,"rpe":true,"hr":true}'::jsonb),
  ('kb-clean',
   'Elevación de una kettlebell desde abajo hasta su apoyo delante del hombro, mediante una extensión de cadera.',
   'Mantén la kettlebell cerca del cuerpo y guía la mano dentro del asa al recibirla. Deja que la carga rodee el antebrazo, sin golpearlo; estabiliza la posición antes de bajar o cambiar de lado.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('power-clean',
   'Cargada de barra desde el suelo hasta los hombros, con recepción por encima de una sentadilla profunda.',
   'Separa la barra del suelo con piernas y tronco coordinados. Mantén la barra cerca al extender la cadera y pasa los codos hacia delante para recibirla sobre los hombros, sin sostenerla solo con las manos.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('hang-power-clean',
   'Cargada de barra desde una posición de suspensión hasta los hombros, con recepción alta.',
   'Parte de la altura de suspensión indicada y mantén la barra cerca de los muslos. Extiende piernas y cadera, entra debajo de la barra y recibe con los codos hacia delante y los pies estables.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('sandbag-clean',
   'Elevación de un saco desde abajo hasta una posición de apoyo delante del pecho o sobre los hombros, según la variante.',
   'Acerca el saco al cuerpo y asegura la sujeción antes de levantarlo. Impulsa la carga con piernas y cadera, recoge el saco sin alejarlo del tronco y estabiliza su apoyo antes de bajarlo.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('clean-and-jerk',
   'Levantamiento de barra en dos fases: cargada a los hombros y envión hasta un apoyo estable sobre la cabeza.',
   'Recibe primero la barra sobre los hombros y recupera el equilibrio. Inicia el envión con una flexión corta de piernas, impulsa la barra y colócate debajo; estabiliza la recepción indicada antes de reunir los pies.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('run',
   'Desplazamiento de carrera en exterior o sobre una cinta, siguiendo el objetivo de la sesión.',
   'Mantén una postura natural y deja que los brazos acompañen la zancada. Apoya los pies cerca del cuerpo sin forzar una longitud de paso; adapta el ritmo al terreno y al esfuerzo indicado.', '{"time":true,"distance":true,"rpe":true,"hr":true}'::jsonb),
  ('bicep-curl',
   'Flexión del codo para acercar la carga al brazo; material, agarre y ejecución alterna o simultánea los indica la prescripción.',
   'Mantén el tronco estable y los hombros relajados. Flexiona los codos sin impulsar la carga con la espalda y baja de forma controlada, conservando el agarre indicado durante todo el gesto.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('w23-nordic-curl',
   'Descenso del cuerpo desde una posición de rodillas, frenado por los isquios con los tobillos sujetos en un apoyo estable.',
   'Asegura la sujeción de los tobillos y alinea hombros, cadera y rodillas. Inclínate hacia delante sin doblar la cadera; utiliza el apoyo o la asistencia indicada para controlar el descenso y volver.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('serratus-wall-slide',
   'Deslizamiento de los brazos por una pared, manteniendo un apoyo suave para acompañar el movimiento de las escápulas.',
   'Apoya los antebrazos o las manos según la variante. Desliza hacia arriba sin encoger los hombros ni arquear la espalda; conserva una presión suave contra la pared y baja con control.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('devil-press',
   'Movimiento con mancuernas que combina un burpee con la elevación de la carga hasta un apoyo sobre la cabeza.',
   'Usa mancuernas estables para apoyar las manos y controla el descenso al suelo. Acerca los pies, impulsa la carga con la cadera y estabiliza los brazos arriba sin arquear la espalda; baja con control para reiniciar.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('double-under',
   'Salto de comba en el que la cuerda pasa dos veces bajo los pies durante un mismo salto.',
   'Mantén los codos cerca del cuerpo y mueve la cuerda desde las muñecas. Salta de forma vertical y aterriza con suavidad; coordina el giro doble sin recoger las rodillas hacia el pecho.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('pull-up',
   'Elevación del cuerpo desde una suspensión en barra hasta acercar el pecho a ella, usando la tracción de los brazos y la espalda.',
   'Empieza con un agarre firme y hombros controlados. Tira sin adelantar la barbilla para buscar la barra y baja con control; usa la asistencia o el estilo indicado sin cambiarlo durante la serie.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('weighted-pullup',
   'Dominada realizada con una carga externa sujeta al cuerpo.',
   'Comprueba que el lastre está bien fijado y no golpea las piernas. Mantén un agarre firme, sube sin balancear la carga y controla la bajada hasta el recorrido indicado.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('prone-t-raise',
   'Elevación de los brazos hacia los lados desde una posición tumbada boca abajo, formando una T con el cuerpo.',
   'Apoya el tronco y mantén el cuello alineado. Eleva los brazos sin encoger los hombros ni despegar el pecho para ganar altura; vuelve al apoyo con control, con o sin la carga indicada.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('prone-y-raise',
   'Elevación de los brazos en diagonal desde una posición tumbada boca abajo, formando una Y con el cuerpo.',
   'Mantén el tronco apoyado y el cuello cómodo. Eleva los brazos en diagonal sin llevar los hombros hacia las orejas ni arquear la espalda; controla el regreso con la carga indicada, si la hay.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('banded-front-raise',
   'Elevación de los brazos por delante del cuerpo contra la resistencia de una banda.',
   'Asegura el apoyo de la banda antes de empezar. Eleva los brazos con el tronco estable y una pequeña flexión de codos, sin impulsar con la espalda; baja manteniendo el control de la tensión.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('lateral-raise',
   'Elevación de los brazos hacia los lados con carga, para trabajar el hombro.',
   'Mantén una pequeña flexión de codos y los hombros lejos de las orejas. Eleva los brazos sin balancear el tronco y desciende con control hasta el inicio.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('hip-thrust',
   'Extensión de cadera con la espalda alta apoyada en un banco y los pies en el suelo.',
   'Asegura el banco y coloca la carga sobre la cadera con el apoyo adecuado. Empuja el suelo con los pies y eleva la pelvis sin terminar arqueando la espalda; baja con control manteniendo el apoyo de la espalda alta.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('hyrox-sled-push',
   'Desplazamiento de un trineo empujando sus agarres mientras se avanza a pie.',
   'Asegura las manos en los agarres y alinea el tronco con la dirección del empuje. Avanza con apoyos firmes y sin perder tensión en el cuerpo. La carga y el recorrido los determina la sesión.', '{"reps":true,"time":true,"rpe":true,"distance":true,"weight":true}'::jsonb),
  ('shrug',
   'Elevación de los hombros contra una carga sostenida con los brazos extendidos.',
   'Mantén el cuello alineado y el tronco estable. Eleva los hombros sin girarlos ni flexionar los codos para ayudar; vuelve a una posición cómoda de forma controlada.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('face-pull',
   'Tracción de una polea o banda hacia la cara, abriendo los brazos y acompañando el movimiento de los hombros.',
   'Asegura la resistencia delante del cuerpo y mantén el tronco estable. Lleva las manos hacia los lados de la cara sin encoger los hombros ni adelantar la cabeza; vuelve conservando el control de la tensión.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('push-up',
   'Flexión y extensión de los codos con las manos apoyadas, desplazando el cuerpo como una unidad.',
   'Ajusta el apoyo de manos y pies a la variante indicada. Mantén abdomen y glúteos activos al bajar y empuja el apoyo sin dejar que la pelvis se hunda ni levantar primero el pecho.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('scapular-push-up',
   'Desplazamiento de las escápulas en una posición de plancha con los codos extendidos.',
   'Mantén los codos sin doblar y el tronco alineado. Deja que el pecho se acerque ligeramente al suelo entre los hombros y después aleja el apoyo empujando con las manos, sin mover la cadera.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('dip',
   'Descenso y elevación del cuerpo entre barras paralelas mediante la flexión y extensión de los codos.',
   'Empieza con un apoyo estable y los hombros controlados. Flexiona los codos hasta un recorrido cómodo, sin dejar caer el cuerpo; empuja las barras para volver y evita balancear las piernas.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('weighted-dip',
   'Fondo en paralelas realizado con una carga externa sujeta al cuerpo.',
   'Asegura el lastre antes de subir a las barras. Mantén los hombros controlados al bajar y empuja para volver sin balancear la carga; termina el descenso antes de perder un apoyo cómodo.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('l-sit',
   'Sostén del cuerpo apoyado en las manos, con las piernas elevadas por delante para formar una L.',
   'Asegura el apoyo de las manos y empuja hacia abajo para separar el cuerpo del suelo. Mantén las piernas en la posición indicada y el tronco estable, sin dejar que los hombros se hundan entre los brazos.', '{"time":true,"rpe":true}'::jsonb),
  ('medicine-ball-throw',
   'Lanzamiento de un balón medicinal; la dirección, el objetivo y la recepción dependen de la variante indicada por el coach.',
   'Usa un balón adecuado para el lanzamiento prescrito y despeja la zona de trayectoria y rebote. Coordina piernas, tronco y brazos sin soltar el apoyo; controla la recepción o deja caer el balón según la variante, sin asumir que todos los balones rebotan.', '{"reps":true,"time":true,"rpe":true,"weight":true}'::jsonb),
  ('turkish-get-up',
   'Paso desde tumbado hasta de pie y regreso al suelo manteniendo una carga estable sobre un brazo.',
   'Mantén la carga alineada sobre el hombro y utiliza los apoyos de mano, codo y rodilla en la secuencia indicada. Estabiliza cada posición antes de avanzar; vuelve al suelo recorriendo los apoyos con control.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('deadlift',
   'Elevación de una carga desde el suelo hasta una posición de pie mediante la extensión de rodillas y cadera.',
   'Acerca la carga al cuerpo y crea tensión antes de despegarla del suelo. Empuja con los pies, extiende piernas y cadera de forma coordinada y controla la bajada sin alejar la carga ni perder la posición del tronco.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('romanian-deadlift',
   'Bisagra de cadera desde una posición de pie, bajando la carga cerca de las piernas con una ligera flexión de rodillas.',
   'Lleva la cadera hacia atrás y mantén la carga cerca del cuerpo. Desciende hasta el recorrido que permita conservar el tronco firme; vuelve extendiendo la cadera sin inclinarte hacia atrás al terminar.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('single-leg-rdl',
   'Bisagra de cadera sobre una pierna, con la otra pierna como contrapeso y la carga indicada.',
   'Mantén el pie de apoyo firme y la rodilla ligeramente flexionada. Lleva la cadera atrás sin abrir la pelvis hacia un lado; vuelve con control y usa el apoyo o la asistencia prescritos si los hay.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('pogo-jump',
   'Saltos cortos y repetidos en vertical, con el impulso concentrado en los tobillos.',
   'Mantén el tronco erguido y las rodillas desbloqueadas. Impúlsate desde el antepié y vuelve a apoyar con control, conservando un ritmo uniforme y sin buscar una sentadilla en cada salto.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('bench-press',
   'Empuje de una carga desde delante del pecho mientras la espalda está apoyada en un banco.',
   'Asegura los pies y el apoyo de la espalda antes de mover la carga. Baja de forma controlada con las muñecas alineadas y empuja sin despegar la pelvis; prepara los soportes o la ayuda necesarios para colocar y retirar el material.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('overhead-press',
   'Empuje de una carga desde la altura de los hombros hasta un apoyo estable sobre la cabeza, sin impulso de piernas.',
   'Mantén abdomen y glúteos activos antes de empujar. Deja pasar la carga cerca de la cara sin arquear la espalda y termina con los brazos estables sobre los hombros; baja con control.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('toes-to-bar',
   'Elevación de los pies hacia una barra desde una suspensión con las manos.',
   'Mantén el agarre y el control de los hombros durante la suspensión. Eleva las piernas con la técnica indicada y controla el regreso, sin perder el apoyo ni aumentar el balanceo para alcanzar la barra.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('push-press',
   'Empuje de una carga sobre la cabeza iniciado con una flexión y extensión corta de piernas.',
   'Mantén la carga apoyada delante de los hombros y flexiona las piernas sin inclinar el pecho. Empuja el suelo y transmite ese impulso a los brazos; estabiliza arriba y controla el regreso a los hombros.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('row',
   'Remo en ergómetro, coordinando el impulso de piernas, la apertura de cadera y la tracción de brazos.',
   'Inicia la palada con las piernas, abre después la cadera y termina acercando el agarre al tronco. Para volver, extiende primero los brazos y recupera cadera y piernas con control, sin golpear el tope delantero.', '{"time":true,"distance":true,"rpe":true,"hr":true,"calories":true}'::jsonb),
  ('band-row',
   'Tracción de una banda hacia el tronco para realizar un remo.',
   'Comprueba el anclaje y tensa la banda antes de empezar. Lleva los codos hacia atrás sin encoger los hombros ni balancear el tronco; estira los brazos con control manteniendo el apoyo estable.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('barbell-row',
   'Tracción de una barra hacia el tronco desde una posición inclinada, manteniendo una bisagra de cadera.',
   'Fija la inclinación del tronco y mantén la barra cerca del cuerpo. Lleva los codos hacia atrás sin levantar el pecho para impulsar la carga; baja de forma controlada conservando la posición de la cadera.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('gorilla-row',
   'Remo desde una posición de bisagra con cargas cerca del suelo, alternando la tracción de los brazos según la variante.',
   'Mantén ambos pies firmes y el tronco estable sobre las cargas. Lleva un codo hacia atrás sin girar la pelvis y devuelve la carga con control; evita levantar el pecho para ayudar a la tracción.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('inverted-row',
   'Tracción del cuerpo hacia una barra baja o un apoyo de suspensión, con los pies apoyados y el tronco alineado.',
   'Asegura la barra o el sistema de suspensión y ajusta la inclinación del cuerpo. Acerca el pecho al apoyo sin adelantar la cabeza ni hundir la pelvis; baja de forma controlada manteniendo la alineación.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('pendlay-row',
   'Remo con barra desde el suelo, reiniciando el apoyo de la carga entre repeticiones con el tronco inclinado.',
   'Coloca el tronco firme antes de cada tracción. Lleva la barra hacia el abdomen sin levantar la cadera para impulsarla y devuélvela al suelo; recupera la tensión antes del siguiente movimiento.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('renegade-row',
   'Remo con una mano desde una plancha apoyada sobre cargas estables, manteniendo el equilibrio con el brazo contrario.',
   'Asegura que las cargas no ruedan y ajusta la separación de los pies. Tira con un brazo sin girar la cadera ni hundir la pelvis; devuelve la carga con control antes de cambiar el apoyo.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('band-scapular-retraction',
   'Retracción de las escápulas contra una banda, con los brazos en la posición indicada.',
   'Tensa la banda sin encoger los hombros. Acerca suavemente las escápulas conservando la posición de codos y tronco; vuelve de forma controlada sin convertir el gesto en un remo completo.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('cable-external-rotation',
   'Rotación del brazo hacia fuera contra la resistencia de una polea, manteniendo el codo en una posición estable.',
   'Ajusta la polea a la posición de trabajo y fija el apoyo del codo indicado. Gira el antebrazo sin separar el codo ni mover el tronco; vuelve con control dentro de un recorrido cómodo.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('box-jump',
   'Salto desde el suelo para aterrizar sobre un cajón estable.',
   'Comprueba que el cajón no se mueve y despeja la zona de apoyo. Impúlsate con piernas y brazos, aterriza con los pies bien apoyados y absorbe el impacto; baja con la técnica indicada antes de repetir.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('w6-high-box-jump',
   'Salto sobre un cajón cuya altura se ha elegido para la sesión, con una recepción estable encima.',
   'Usa una altura que permita apoyar los pies por completo y conservar el equilibrio. Coordina el impulso de piernas y brazos, estabiliza la recepción y baja con control; la altura no sustituye a una buena recepción.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('broad-jump',
   'Salto hacia delante desde el suelo, buscando un desplazamiento horizontal con recepción estable.',
   'Carga el impulso con una flexión de piernas y acompaña con los brazos. Despega hacia delante, aterriza con las rodillas alineadas con los pies y absorbe el impacto antes de reiniciar.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('zercher-squat-jump',
   'Salto desde una sentadilla con una barra sostenida en los pliegues de los codos.',
   'Asegura la barra cerca del tronco y conserva el apoyo de los brazos. Coordina la extensión de piernas con el salto y aterriza con control, sin dejar que la carga arrastre el tronco hacia delante.', '{"reps":true,"time":true,"rpe":true,"weight":true}'::jsonb),
  ('depth-jump',
   'Descenso desde un cajón seguido de un salto, coordinando la recepción en el suelo y el nuevo impulso.',
   'Da un paso para salir del cajón sin saltar hacia arriba desde él. Recibe con un apoyo estable y enlaza el impulso indicado, manteniendo las rodillas alineadas y sin perder el control del tronco.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('lateral-bound',
   'Salto lateral con despegue y recepción sobre una pierna, alternando lados según la secuencia indicada.',
   'Impúlsate hacia un lado sin girar el tronco. Recibe sobre el pie contrario con la rodilla alineada y estabiliza el apoyo antes de enlazar o reiniciar el siguiente salto.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('zig-zag-hop',
   'Secuencia de saltos que avanza alternando diagonales hacia un lado y otro.',
   'Mantén claro el recorrido y dirige el impulso hacia la siguiente diagonal. Aterriza con equilibrio y control de rodillas; conserva el tipo de apoyo y el ritmo indicados sin cruzar los pies.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('pistol-squat',
   'Sentadilla sobre una pierna con la otra pierna elevada por delante del cuerpo.',
   'Mantén el pie de apoyo firme y lleva la rodilla en la dirección de los dedos. Desciende hasta un recorrido controlado sin dejar caer la pelvis; usa el apoyo o contrapeso indicado y vuelve empujando el suelo.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('bulgarian-split-squat',
   'Sentadilla dividida con el pie trasero elevado sobre un apoyo y el pie delantero en el suelo.',
   'Asegura el apoyo trasero y ajusta la separación de los pies. Baja con el peso repartido de forma estable, mantén la rodilla delantera alineada y empuja con la pierna delantera para volver sin perder el equilibrio.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('jump-squat',
   'Sentadilla enlazada con un salto vertical, con la carga o el apoyo indicados en la variante.',
   'Coordina la flexión de piernas con el impulso hacia arriba. Aterriza con los pies estables y absorbe el impacto antes de repetir; si hay carga, conserva su apoyo sin dejar que rebote sobre el cuerpo.', '{"reps":true,"time":true,"rpe":true,"weight":true}'::jsonb),
  ('front-squat',
   'Sentadilla con una barra apoyada delante del cuerpo sobre la parte anterior de los hombros.',
   'Asegura el apoyo de la barra y mantén los codos orientados hacia delante. Desciende con los pies firmes y las rodillas siguiendo los dedos; sube sin dejar que el pecho caiga ni perder el apoyo de la barra.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('goblet-squat',
   'Sentadilla sosteniendo una mancuerna o kettlebell delante del pecho.',
   'Mantén la carga cerca del tronco y ambos pies firmes. Desciende dejando que las rodillas sigan la dirección de los dedos y vuelve empujando el suelo, sin alejar la carga para compensar.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('air-squat',
   'Sentadilla realizada sin carga externa, flexionando cadera y rodillas desde una posición de pie.',
   'Apoya toda la planta de los pies y deja que las rodillas sigan su dirección. Baja hasta un recorrido controlado y vuelve sin perder el equilibrio ni despegar los talones para ganar profundidad.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('skater-squat',
   'Sentadilla sobre una pierna con la otra pierna flexionada hacia atrás, con apoyo o contrapeso según la variante.',
   'Mantén el pie delantero firme y la rodilla alineada. Lleva la pierna libre hacia atrás al bajar sin girar la pelvis; vuelve empujando con la pierna de apoyo y conserva el contrapeso indicado.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('back-squat',
   'Sentadilla con una barra apoyada sobre la espalda alta, en la posición indicada por el coach.',
   'Asegura la barra y crea tensión en el tronco antes de bajar. Mantén los pies apoyados y las rodillas siguiendo los dedos; vuelve con piernas y cadera coordinadas, conservando el apoyo de la barra.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('ski-erg',
   'Trabajo en ergómetro de esquí, coordinando la tracción de los brazos con el movimiento de cadera y rodillas.',
   'Inicia la tracción con los hombros y acompaña con una flexión controlada de cadera y rodillas. Termina el recorrido sin colgarte de los agarres y recupera la posición con suavidad, manteniendo un ritmo uniforme.', '{"time":true,"distance":true,"rpe":true,"hr":true,"calories":true}'::jsonb),
  ('box-step-up',
   'Subida a un cajón o escalón mediante el apoyo de un pie, con o sin carga externa.',
   'Apoya el pie por completo sobre una superficie estable. Empuja con la pierna de arriba para subir sin impulsarte en exceso con la pierna de abajo; controla la bajada y el cambio de lado indicado.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('dead-hang',
   'Suspensión sostenida en una barra con el cuerpo separado del suelo.',
   'Asegura el agarre antes de quitar el apoyo de los pies. Mantén la posición de hombros indicada y evita balancearte; utiliza un apoyo cercano para salir de la suspensión con control.', '{"time":true,"rpe":true}'::jsonb),
  ('kb-swing',
   'Balanceo de una kettlebell impulsado mediante una bisagra y una extensión de cadera.',
   'Lleva la cadera hacia atrás manteniendo la carga cerca del cuerpo. Extiende la cadera para impulsar la kettlebell sin levantarla solo con los brazos; recibe su regreso con otra bisagra y el tronco firme.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('thruster',
   'Movimiento continuo que combina una sentadilla con un empuje de la carga sobre la cabeza.',
   'Mantén la carga apoyada delante de los hombros durante la sentadilla. Usa el impulso de las piernas al subir para iniciar el press y estabiliza la carga arriba, sin arquear la espalda; vuelve al apoyo antes de bajar de nuevo.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('hyrox-farmer-carry',
   'Transporte a pie de dos cargas, una a cada lado del cuerpo, manteniendo los brazos extendidos.',
   'Asegura el agarre y camina con el tronco estable y los hombros controlados. Si necesitas descansar, deposita las cargas sin seguir avanzando y retoma desde ese punto. La carga y el recorrido los indica la sesión.', '{"reps":true,"time":true,"rpe":true,"distance":true,"weight":true}'::jsonb),
  ('run-technique-drills',
   'Trabajo de coordinación y técnica de carrera; cada ejercicio concreto y su secuencia los indica el coach.',
   'Realiza el gesto indicado con un apoyo estable y un tronco erguido. Coordina brazos y piernas sin buscar velocidad a costa de perder el movimiento; sigue el recorrido, ritmo y tipo de apoyo de la variante prescrita.', '{"reps":true,"time":true,"distance":true,"rpe":true}'::jsonb),
  ('hyrox-wall-balls',
   'Sentadilla con un balón sostenido delante del pecho, enlazada con un lanzamiento hacia una diana y la recepción del balón.',
   'Mantén el balón cerca del pecho al bajar y usa el impulso de las piernas para lanzarlo. Dirige el balón al objetivo y recíbelo con control antes de la siguiente sentadilla. Carga, diana y repeticiones las fija la sesión o el reglamento aplicable.', '{"reps":true,"time":true,"rpe":true,"weight":true}'::jsonb),
  ('wall-climb',
   'Desplazamiento desde una plancha con los pies cerca de una pared hasta una posición más vertical, caminando con manos y pies.',
   'Empieza con manos y pies estables y conserva la tensión del tronco. Acerca las manos mientras subes los pies sin arquear la espalda; invierte el recorrido con control y termina antes de perder los apoyos.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('lunge-to-high-knee',
   'Zancada enlazada con un impulso de la pierna de apoyo y la elevación de la rodilla contraria.',
   'Mantén estable el pie de apoyo durante la zancada. Impulsa el cuerpo y eleva la rodilla sin girar la pelvis; controla la recepción y el regreso a la siguiente zancada.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('walking-lunge',
   'Zancadas hacia delante encadenadas para avanzar, con la carga o el apoyo indicados.',
   'Da un paso que permita apoyar el pie delantero con estabilidad. Flexiona ambas piernas sin girar la pelvis y empuja para avanzar al siguiente apoyo; conserva la posición de la carga durante el recorrido.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('w23-kb-overhead-walking-lunge',
   'Zancadas caminando con una kettlebell sostenida sobre la cabeza con un brazo.',
   'Estabiliza la kettlebell sobre el hombro y mantén el codo extendido. Avanza con apoyos firmes sin inclinar el tronco hacia un lado ni arquear la espalda; cambia de lado según la prescripción.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('jump-lunge',
   'Saltos encadenados desde una posición de zancada, cambiando la posición de las piernas en el aire según la variante.',
   'Asegura primero la posición de zancada y coordina el impulso de ambas piernas. Recibe con control y las rodillas alineadas; conserva el equilibrio antes de enlazar el siguiente salto.', '{"reps":true,"time":true,"rpe":true}'::jsonb),
  ('reverse-lunge',
   'Zancada realizada dando un paso hacia atrás desde una posición de pie.',
   'Mantén firme el pie delantero y lleva el otro pie atrás con espacio suficiente para bajar. Flexiona ambas piernas sin girar la pelvis y vuelve empujando con la pierna delantera, conservando el equilibrio.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('lateral-lunge',
   'Zancada hacia un lado, flexionando la pierna que recibe el peso mientras la otra permanece más extendida.',
   'Apoya el pie del lado al que avanzas y lleva la cadera hacia atrás. Mantén el tronco estable y la rodilla alineada con el pie; empuja ese apoyo para volver sin arrastrar la otra pierna.', '{"reps":true,"weight":true,"rpe":true}'::jsonb),
  ('hyrox-sandbag-lunges',
   'Zancadas caminando con un saco apoyado sobre los hombros, manteniendo el control de la carga durante el avance.',
   'Asegura el saco antes de empezar y conserva su apoyo. Da cada paso con equilibrio, baja la rodilla trasera al suelo cuando lo exija el estándar indicado y vuelve sin girar la pelvis. Carga y recorrido los fija la sesión.', '{"reps":true,"time":true,"rpe":true,"distance":true,"weight":true}'::jsonb)
) as v(slug, description, cues, metrics)
where e.slug = v.slug
  and e.coach_id is null
  and e.archived_at is null
  and (e.description is distinct from v.description
    or e.cues is distinct from v.cues
    or e.default_metrics_json = '{}'::jsonb);

-- Material: alternativas reales y apoyos necesarios; no crea variantes como ejercicios nuevos.
update exercises as e
set equipment = v.equipment, updated_at = now()
from (values
  ('walk', array['bodyweight']::text[]),
  ('run-technique-drills', array['bodyweight']::text[]),
  ('weighted-pullup', array['bodyweight','pull_up_bar','dip_belt','plate']::text[]),
  ('weighted-dip', array['bodyweight','parallel_bars','dip_belt','plate']::text[]),
  ('prone-y-raise', array['bodyweight','dumbbell']::text[]),
  ('prone-t-raise', array['bodyweight','dumbbell']::text[]),
  ('good-morning', array['barbell','resistance_band','pvc_pipe']::text[]),
  ('face-pull', array['cable','resistance_band']::text[]),
  ('band-row', array['resistance_band']::text[]),
  ('inverted-row', array['barbell','rack','rope','rings','suspension_trainer']::text[]),
  ('l-sit', array['parallel_bars','rope','rings']::text[]),
  ('bicep-curl', array['dumbbell','barbell','cable','resistance_band']::text[]),
  ('deadlift', array['barbell','dumbbell','kettlebell']::text[]),
  ('romanian-deadlift', array['barbell','dumbbell','kettlebell']::text[]),
  ('single-leg-rdl', array['bodyweight','dumbbell','kettlebell']::text[]),
  ('bench-press', array['barbell','dumbbell','bench']::text[]),
  ('overhead-press', array['barbell','dumbbell','kettlebell']::text[]),
  ('push-press', array['barbell','dumbbell','kettlebell']::text[]),
  ('thruster', array['barbell','dumbbell','kettlebell']::text[]),
  ('walking-lunge', array['bodyweight','barbell','dumbbell','kettlebell']::text[]),
  ('reverse-lunge', array['bodyweight','barbell','dumbbell','kettlebell']::text[]),
  ('bulgarian-split-squat', array['bodyweight','dumbbell','kettlebell','barbell','bench']::text[]),
  ('box-step-up', array['bodyweight','box','dumbbell','kettlebell']::text[]),
  ('skater-squat', array['bodyweight','plate','dumbbell']::text[])
) as v(slug, equipment)
where e.slug = v.slug
  and e.coach_id is null
  and e.archived_at is null
  and e.equipment is distinct from v.equipment;

-- Músculos: solo completa las cuatro fichas que carecen de ellos en el inventario.
update exercises as e
set primary_muscle_groups = v.muscles, updated_at = now()
from (values
  ('walk', array['quads','hamstrings','glutes','calves']::text[]),
  ('run-technique-drills', array['quads','hamstrings','glutes','calves','core']::text[]),
  ('w6-high-box-jump', array['quads','glutes','calves']::text[]),
  ('w9-burpee-to-plate', array['quads','glutes','calves','chest','triceps','core']::text[])
) as v(slug, muscles)
where e.slug = v.slug
  and e.coach_id is null
  and e.archived_at is null
  and cardinality(e.primary_muscle_groups) = 0;
