-- 0285 — CONTENIDO DE CORE/MOVILIDAD Y VOCABULARIO DE LANZAMIENTO
-- Fuente del inventario: docs/auditoria-biblioteca-ejercicios-2026-10-01.json.
-- 55 fichas globales activas reciben explicación y claves originales en español.
-- 25 movimientos nuevos; la flexión de rodilla en gemelos es un calificador,
-- no otra identidad (0205). No se altera la voz privada de ningún entrenador.
-- Las claves explican la ejecución, no prescriben dosis ni una metodología.
-- No vídeos inventados, borrados, reactivaciones ni cambios de prescripciones.

with content(slug, description, cues, equipment_fix, muscles_if_empty) as (values
  ('sit-up',
   'Desde tumbado boca arriba con las rodillas flexionadas, eleva el tronco hasta sentarte y vuelve al suelo de forma controlada.',
   'Mantén los pies apoyados. Inicia el movimiento con el abdomen y evita tirar de la cabeza con las manos. Desciende sin dejar caer el tronco.', null::text[], null::text[]),
  ('w6-sit-up-shoot',
   'Abdominal desde el suelo con un balón, seguido de un lanzamiento con ambas manos hacia un objetivo frontal al incorporarte.',
   'Sujeta el balón cerca del pecho durante el abdominal. Coordina la incorporación con el lanzamiento. Usa un balón y una pared o receptor adecuados; el objetivo del lanzamiento lo indica el coach.', null, array['core','hip_flexors','shoulders']),
  ('hand-open-close',
   'Abre las manos extendiendo y separando los dedos y ciérralas después formando un puño sin apretar al máximo.',
   'Mantén los antebrazos quietos y las muñecas alineadas. Recorre la apertura y el cierre sin movimientos bruscos. Relaja las manos entre repeticiones.', null, null),
  ('leg-swings',
   'De pie junto a un apoyo, balancea una pierna desde la cadera mientras la otra sostiene el cuerpo. El coach puede indicar balanceos frontales o laterales.',
   'Sujétate para estabilizarte. Mantén el tronco quieto y aumenta el recorrido gradualmente. Mueve la pierna desde la cadera sin buscar altura con la espalda.', null, null),
  ('bird-dog',
   'En cuadrupedia, extiende un brazo y la pierna contraria, vuelve al apoyo y cambia de diagonal.',
   'Coloca las manos bajo los hombros y las rodillas bajo las caderas. Alarga brazo y pierna sin elevarlos por encima del tronco. Mantén la pelvis paralela al suelo.', null, null),
  ('fire-hydrant',
   'En cuadrupedia y con la rodilla flexionada, separa una pierna hacia el lateral y vuelve al apoyo.',
   'Mantén las manos firmes y el abdomen activo. Eleva la rodilla sin girar la pelvis ni desplazar todo el peso al otro lado. Controla el regreso.', null, null),
  ('body-saw',
   'Desde una plancha de antebrazos sobre las puntas de los pies, desplaza el cuerpo ligeramente hacia delante y hacia atrás como una unidad.',
   'Empuja el suelo con los antebrazos. Mantén hombros, pelvis y tobillos alineados. Usa un recorrido que permita mover el cuerpo sin hundir la zona lumbar.', null, null),
  ('hip-cars',
   'De pie con un apoyo, recorre un círculo controlado con una cadera: lleva la rodilla al frente, abre hacia el lateral y conduce la pierna hacia atrás.',
   'Mantén el tronco y la pelvis orientados al frente. Haz el círculo despacio y sin impulso. Reduce el recorrido si necesitas inclinar o girar el cuerpo.', null, null),
  ('clamshell',
   'Tumbado de lado con las caderas y rodillas flexionadas y una banda alrededor de las piernas, abre la rodilla superior manteniendo los pies juntos.',
   'Apila las caderas una sobre otra. Abre desde la cadera sin rodar la pelvis hacia atrás. Mantén la banda bajo control al cerrar.', null, null),
  ('leg-cradle',
   'De pie, acerca una pierna flexionada hacia el tronco sosteniendo la rodilla y el tobillo, y vuelve a apoyarla antes de cambiar de lado.',
   'Mantén erguido el tronco y estable la pierna de apoyo. Sostén la pierna sin forzar la rodilla ni girar el tobillo. Lleva la cadera al recorrido que controles.', null, null),
  ('w23-dead-bug',
   'Tumbado boca arriba con brazos elevados y caderas y rodillas flexionadas, aleja un brazo y la pierna contraria y vuelve antes de cambiar de diagonal.',
   'Mantén las costillas recogidas y la pelvis estable. Extiende solo hasta donde puedas conservar el control del tronco. Respira mientras alternas los lados.', null, null),
  ('shoulder-dislocates',
   'Con una pica o banda sujeta con ambas manos y agarre amplio, pasa los brazos desde delante del cuerpo por encima de la cabeza y hacia atrás.',
   'Usa un agarre que permita pasar sin doblar los codos ni arquear la espalda. Mantén las costillas recogidas. La pica guía el movimiento, no empuja los hombros al final del recorrido.', null, null),
  ('worlds-greatest-stretch',
   'Desde una zancada larga con las manos apoyadas, acerca un codo al interior del pie delantero y gira después el tronco abriendo ese brazo hacia arriba.',
   'Mantén estable el pie delantero y adapta el apoyo de la rodilla trasera. Gira desde el tronco sin desplazar la pelvis. Vuelve al apoyo antes de cambiar de lado.', null, null),
  ('hanging-knee-raise',
   'Colgado de una barra, eleva las rodillas hacia el tronco y desciende las piernas manteniendo el cuerpo bajo control.',
   'Activa el agarre y los hombros. Lleva la pelvis hacia delante al subir las rodillas. Evita balancearte para iniciar la siguiente repetición.', null, null),
  ('thread-the-needle',
   'En cuadrupedia, pasa un brazo por debajo del otro mientras giras el tronco y acercas ese hombro al suelo; vuelve a la posición inicial.',
   'Mantén las caderas sobre las rodillas. Permite que el tronco rote sin desplazar la pelvis. Apoya el hombro de forma gradual y sin cargar el peso sobre el cuello.', null, null),
  ('scorpion-stretch',
   'Tumbado boca abajo con los brazos abiertos, flexiona una rodilla y lleva ese pie hacia el lado contrario mediante un giro controlado de la pelvis.',
   'Mantén los hombros cerca del suelo. Deja que la cadera gire sin impulsar la pierna. Acorta el recorrido antes de forzar la espalda para alcanzar el suelo.', null, null),
  ('hip-90-90-stretch',
   'Sentado con una pierna delante y la otra al lateral, ambas rodillas flexionadas aproximadamente en ángulo recto, mantén la posición de caderas 90/90.',
   'Distribuye el apoyo entre ambos lados de la pelvis. Inclina el tronco desde la cadera si el coach indica avanzar sobre la pierna delantera. No presiones las rodillas contra el suelo.', null, null),
  ('standing-quad-stretch',
   'De pie, flexiona una rodilla y sujeta el pie de ese lado por detrás del cuerpo para mantener un estiramiento de la parte delantera del muslo.',
   'Usa un apoyo si lo necesitas para equilibrarte. Mantén las rodillas cerca y la pelvis estable. Acerca el talón sin tirar con fuerza del pie ni arquear la espalda.', null, null),
  ('hip-flexor-stretch',
   'En posición de media rodilla, con un pie delante y la otra rodilla apoyada, lleva suavemente la pelvis hacia delante manteniendo el tronco erguido.',
   'Recoge ligeramente la pelvis antes de avanzar. Mantén la cadera trasera alineada y evita buscar recorrido arqueando la espalda. Usa un apoyo acolchado bajo la rodilla.', null, null),
  ('calf-stretch',
   'De pie frente a un apoyo, coloca una pierna detrás y acerca el cuerpo al apoyo manteniendo el talón trasero en el suelo.',
   'Orienta el pie trasero al frente y conserva el talón apoyado. El coach puede indicar rodilla extendida o flexionada; mantén la posición elegida sin rebotes. No gires el pie para ganar recorrido.', null, null),
  ('frog-stretch',
   'En el suelo con las rodillas separadas y flexionadas, apoya las manos o los antebrazos y lleva la pelvis ligeramente hacia atrás.',
   'Acolcha el apoyo de las rodillas. Mantén los pies alineados con las piernas y la espalda bajo control. Ajusta la separación sin empujar las rodillas para ampliar la postura.', null, null),
  ('couch-stretch',
   'En media rodilla frente a un banco o pared, eleva el pie de la pierna trasera contra el apoyo y mantén el tronco erguido.',
   'Acolcha la rodilla trasera y ajusta su distancia al apoyo. Mantén la pelvis recogida. Acerca el tronco a la vertical sin arquear la zona lumbar.', null, null),
  ('quadruped-hip-extension',
   'En cuadrupedia, extiende una cadera llevando la pierna hacia atrás y vuelve al apoyo. La rodilla puede mantenerse flexionada según la variante indicada.',
   'Mantén manos y rodillas estables. Eleva la pierna desde la cadera sin arquear la espalda. Conserva la pelvis orientada al suelo durante el regreso.', null, null),
  ('banded-hip-flexion',
   'De pie con apoyo y una banda que resiste desde atrás, eleva una rodilla hacia delante y vuelve a apoyar el pie de manera controlada.',
   'Fija la banda a un anclaje estable y conserva erguido el tronco. Eleva la rodilla desde la cadera sin inclinarte hacia atrás. Controla la tensión al bajar.', null, null),
  ('banded-wrist-flexion',
   'Con el antebrazo apoyado y la palma hacia arriba, flexiona la muñeca contra la resistencia de una banda y vuelve a la posición inicial.',
   'Mantén quieto el antebrazo y sujeta bien la banda. Mueve la muñeca sin acompañar con el codo. Controla el regreso sin dejar que la banda tire de la mano.', null, null),
  ('foam-roll',
   'Coloca un rodillo bajo la región muscular indicada y desplaza el cuerpo sobre él de forma controlada para recorrer esa zona.',
   'Usa las manos y la otra pierna para graduar el peso sobre el rodillo. Recorre el músculo sin pasar sobre articulaciones ni prominencias óseas. La región y el tiempo los elige el coach.', null, null),
  ('cat-cow',
   'En cuadrupedia, alterna redondear la columna con extenderla suavemente mientras la pelvis acompaña el movimiento.',
   'Mantén manos bajo hombros y rodillas bajo caderas. Reparte el movimiento a lo largo del tronco. Deja que la cabeza acompañe sin llevar el cuello bruscamente al extremo.', null, null),
  ('landmine-twist',
   'De pie, sujeta con ambas manos el extremo libre de una barra anclada por el otro extremo y desplázalo de un lado al otro con control.',
   'Comprueba el anclaje antes de empezar. Gira las caderas y permite que los pies acompañen para no retorcer las rodillas. Conserva el tronco firme y controla el cambio de dirección.', null, null),
  ('russian-twist',
   'Sentado con el tronco ligeramente inclinado, gira el pecho alternadamente hacia ambos lados, con las manos juntas o sujetando la carga indicada.',
   'Mantén la espalda alargada y los pies apoyados salvo variante explícita. Gira el tronco, no solo las manos. Controla el cambio de lado sin dejar caer la carga.', null, null),
  ('hollow-hold',
   'Tumbado boca arriba, eleva ligeramente hombros y piernas y mantén una posición compacta del tronco sin perder el apoyo lumbar.',
   'Recoge las costillas y acerca la pelvis al tronco. Dobla las rodillas o acerca los brazos si necesitas acortar la palanca. Mantén el cuello alineado y sigue respirando.', null, null),
  ('glute-bridge-isometric-hold',
   'Desde tumbado boca arriba con rodillas flexionadas y pies apoyados, eleva la pelvis y mantén la posición de puente.',
   'Empuja el suelo con los pies. Mantén las rodillas alineadas con ellos y la pelvis nivelada. Conserva la altura sin arquear la espalda ni contener la respiración.', null, null),
  ('cable-woodchop',
   'De pie junto a una polea alta, lleva el agarre con ambas manos en diagonal hacia el lado contrario y vuelve controlando la resistencia.',
   'Mantén el agarre cerca de la trayectoria del tronco. Permite que las caderas y los pies acompañen el giro. Controla el regreso sin dejar que la polea te arrastre; la dirección alternativa la indica el coach.', null, null),
  ('open-book-stretch',
   'Tumbado de lado con las rodillas flexionadas y los brazos juntos delante del pecho, abre el brazo superior hacia atrás mientras gira el tronco.',
   'Mantén las rodillas juntas y apoyadas. Sigue la mano con la mirada sin tirar del cuello. Abre hasta donde puedas conservar la pelvis estable y vuelve suavemente.', null, null),
  ('glute-bridge-march',
   'Desde un puente de glúteo, despega alternativamente un pie del suelo manteniendo elevada la pelvis.',
   'Estabiliza primero el puente sobre ambos pies. Levanta el pie sin inclinar la pelvis ni perder altura. Apoya de nuevo antes de cambiar de pierna.', null, null),
  ('windmill-stretch',
   'De pie con las piernas separadas, gira el tronco y lleva una mano hacia el pie contrario mientras el otro brazo se abre hacia arriba.',
   'Inclínate desde las caderas y mantén las rodillas en una posición cómoda. Sigue la mano superior con la mirada si puedes mantener el cuello relajado. No fuerces llegar al suelo.', null, null),
  ('mountain-climber',
   'Desde una plancha alta sobre las manos, acerca alternativamente una rodilla hacia el pecho y devuelve el pie a su apoyo.',
   'Mantén las manos bajo los hombros. Conserva la pelvis estable al cambiar de pierna. Ajusta la velocidad para no hundir la espalda ni rebotar con las caderas.', null, null),
  ('ankle-dorsiflexion-mobilization',
   'En media rodilla frente a una pared, acerca la rodilla delantera a la pared mientras el talón de ese pie permanece apoyado.',
   'Orienta la rodilla en la dirección de los dedos. Ajusta la distancia a la pared para llegar sin levantar el talón. Evita que el arco del pie se hunda para ganar recorrido.', null, null),
  ('inchworm',
   'Desde de pie, inclínate hacia el suelo y camina con las manos hasta una plancha; acerca después los pies a las manos y vuelve a incorporarte.',
   'Flexiona las rodillas lo necesario para apoyar las manos. Conserva el tronco controlado al llegar a la plancha. Avanza con pasos cortos y evita dejar caer las caderas.', null, null),
  ('monster-walk',
   'Con una banda alrededor de las piernas y ligera flexión de caderas y rodillas, avanza en pasos diagonales alternando ambas piernas.',
   'Mantén tensión en la banda y los pies orientados al frente. Da pasos que permitan conservar la altura de la pelvis. Acerca el pie de apoyo sin juntar por completo las piernas.', null, null),
  ('side-step-squat-band',
   'Con una banda alrededor de las piernas, mantén una posición de sentadilla parcial y desplázate lateralmente sin perder la postura.',
   'Mantén las rodillas en la dirección de los pies y el tronco estable. Abre con un pie y acerca después el otro conservando tensión. Evita subir y bajar la pelvis en cada paso.', null, null),
  ('stability-ball-pike',
   'Desde una plancha alta con las piernas apoyadas sobre un fitball, eleva la pelvis y acerca el balón a las manos manteniendo las rodillas extendidas.',
   'Apoya las manos bajo los hombros y comprueba que el balón puede rodar sin obstáculos. Eleva la pelvis desde el abdomen sin doblar las rodillas para convertirlo en una recogida. Vuelve a la plancha sin hundir la espalda.', array['stability_ball'], null),
  ('plank',
   'Mantén una plancha sobre antebrazos y puntas de los pies con el cuerpo alineado desde los hombros hasta los tobillos.',
   'Coloca los codos bajo los hombros y empuja el suelo. Mantén las costillas recogidas y la pelvis estable. Respira sin hundir la zona lumbar ni elevar demasiado las caderas.', null, null),
  ('plank-up-down',
   'Desde una plancha de antebrazos, apoya una mano y después la otra para pasar a plancha alta; regresa a los antebrazos con control.',
   'Mantén la pelvis orientada al suelo. Coloca cada mano bajo su hombro y evita balancearte al cambiar de apoyo. Alterna el brazo que inicia según indique el coach.', null, null),
  ('side-plank',
   'Tumbado de lado, apóyate sobre un antebrazo y el lateral de los pies y eleva la pelvis para mantener una línea entre hombros, caderas y tobillos.',
   'Coloca el codo bajo el hombro y empuja el suelo. Mantén las caderas apiladas sin girar el tronco. La variante con rodillas apoyadas conserva la misma alineación del tronco.', null, null),
  ('cobra-pose',
   'Tumbado boca abajo con las manos junto al pecho, eleva suavemente el pecho mientras la pelvis permanece apoyada en el suelo.',
   'Mantén los codos cerca del cuerpo y los hombros alejados de las orejas. Reparte la extensión por el tronco sin empujar al máximo con los brazos. Vuelve al apoyo de forma gradual.', null, null),
  ('pigeon-pose',
   'Desde el suelo, coloca una pierna flexionada por delante del cuerpo y la otra extendida hacia atrás para mantener un estiramiento de cadera.',
   'Ajusta la posición del pie delantero sin forzar la rodilla. Mantén la pelvis orientada al frente y usa apoyo bajo ella si hace falta. Inclina el tronco solo dentro del recorrido que controles.', null, null),
  ('pallof-press',
   'De pie de lado a una polea o banda, sujeta el agarre delante del pecho, extiende los brazos al frente y vuelve sin girar el tronco.',
   'Comprueba el anclaje y apoya ambos pies con firmeza. Mantén pecho y pelvis mirando al frente. Resiste el tirón lateral tanto al extender como al recoger las manos.', null, null),
  ('glute-bridge',
   'Tumbado boca arriba con las rodillas flexionadas y los pies apoyados, eleva la pelvis hasta formar un puente y vuelve al suelo.',
   'Empuja el suelo con los pies y mantén las rodillas alineadas. Eleva desde las caderas sin arquear la espalda. Desciende la pelvis de forma controlada.', null, null),
  ('single-leg-glute-bridge',
   'Desde tumbado boca arriba, mantén un pie apoyado y la otra pierna sin apoyo; eleva y baja la pelvis usando la pierna apoyada.',
   'Mantén ambas caderas a la misma altura. Empuja con el pie de apoyo sin girar el tronco. Ajusta la altura antes de perder el control de la pelvis.', null, null),
  ('walking-knee-hug',
   'Camina elevando una rodilla hacia el pecho y sujetándola con las manos antes de apoyar ese pie y repetir con la otra pierna.',
   'Mantén erguido el tronco y estable el pie de apoyo. Acerca la rodilla sin encorvarte ni tirar con fuerza. Suelta la pierna antes de dar el siguiente paso.', null, null),
  ('thoracic-rotation',
   'Tumbado de lado con las rodillas flexionadas, abre el brazo superior hacia atrás para girar el tronco mientras la pelvis permanece estable.',
   'Mantén las rodillas juntas y apoyadas. Deja que la mirada acompañe la mano sin forzar el cuello. Abre el brazo y vuelve al inicio sin arrastrar la pelvis.', null, null),
  ('ab-wheel',
   'De rodillas, sujeta una rueda abdominal con ambas manos y ruédala hacia delante antes de volver manteniendo estable el tronco.',
   'Comienza con la rueda bajo los hombros. Mantén las costillas recogidas y mueve hombros y caderas de forma coordinada. Acorta el recorrido antes de hundir la espalda.', null, null),
  ('cossack-squat',
   'Con las piernas separadas, flexiona una rodilla y desplaza la pelvis hacia ese lado mientras la otra pierna permanece extendida.',
   'Mantén el pie de la pierna flexionada apoyado y la rodilla en su dirección. Ajusta la profundidad sin perder el control del tronco. Vuelve al centro antes de cambiar de lado.', null, null),
  ('plank-shoulder-tap',
   'Desde una plancha alta, despega una mano y toca el hombro contrario, devuelve la mano al suelo y alterna los lados.',
   'Separa los pies lo necesario para estabilizarte. Mantén pecho y pelvis orientados al suelo. Toca el hombro sin rotar el tronco ni hundir la zona lumbar.', null, null),
  ('w6-breathing-work',
   'Tumbado boca arriba con las rodillas flexionadas, observa una respiración cómoda dejando que el abdomen y las costillas inferiores acompañen cada ciclo.',
   'Relaja los hombros y la mandíbula. Puedes apoyar una mano en el abdomen y otra sobre las costillas para notar el movimiento. Respira sin forzar la profundidad ni retener el aire; cualquier pauta concreta la elige el coach.', array['bodyweight'], array['diaphragm','intercostals'])
), enriched as (
  select e.id, c.description, c.cues,
    coalesce(c.equipment_fix, e.equipment) as equipment,
    case when cardinality(e.primary_muscle_groups) = 0
      then coalesce(c.muscles_if_empty, e.primary_muscle_groups)
      else e.primary_muscle_groups end as primary_muscle_groups
  from exercises e join content c on c.slug = e.slug
  where e.coach_id is null and e.archived_at is null
    and e.category in ('core','mobility')
)
update exercises e set description = c.description, cues = c.cues,
  equipment = c.equipment, primary_muscle_groups = c.primary_muscle_groups,
  updated_at = now()
from enriched c where e.id = c.id
  and (e.description, e.cues, e.equipment, e.primary_muscle_groups)
    is distinct from (c.description, c.cues, c.equipment, c.primary_muscle_groups);

-- Las métricas son capacidades del movimiento, no cantidades prescritas.
-- Claves admitidas por shared/schema/exercises.ts: reps/time/distance/weight/rpe.
insert into exercises
  (slug, name, name_en, name_es, category, modality, movement_pattern,
   is_unilateral, implement_count, equipment, primary_muscle_groups,
   default_metrics_json, description, cues, source, coach_id)
select v.slug, v.name_en, v.name_en, v.name_es, v.category::exercise_category,
  v.modality, v.pattern, v.unilateral, null::integer, v.equipment, v.muscles,
  v.metrics::jsonb, v.description, v.cues, 'catalog_launch_2026_10', null
from (values
  ('single-under','Single Under','Salto simple de comba','plyometric','functional','jump',false,
   array['jump_rope'],array['calves','shoulders','core'],'{"reps":true,"time":true,"rpe":true}',
   'Salta con ambos pies mientras la comba pasa una vez por debajo de ellos en cada salto.',
   'Gira la comba principalmente desde las muñecas. Mantén los codos cerca del cuerpo y salta lo necesario para dejar pasar la cuerda. Aterriza con control sin golpear los talones.'),
  ('jumping-jack','Jumping Jack','Saltos de apertura','plyometric','functional','jump',false,
   array['bodyweight'],array['calves','glutes','shoulders'],'{"reps":true,"time":true,"rpe":true}',
   'Desde de pie con los pies juntos, salta separando las piernas y elevando los brazos; vuelve a juntar los pies al bajar los brazos.',
   'Coordina brazos y piernas. Aterriza con las rodillas orientadas hacia los pies y sin bloquearlas. La apertura y el regreso forman una repetición completa.'),
  ('high-knees','High Knees','Rodillas altas','skill','functional','locomotion',false,
   array['bodyweight'],array['hip_flexors','calves','core'],'{"distance":true,"time":true,"rpe":true}',
   'Corre con pasos cortos elevando alternativamente las rodillas al frente, en el sitio o avanzando según la prescripción.',
   'Mantén el tronco erguido y los apoyos bajo el cuerpo. Coordina los brazos con la pierna contraria. La distancia o el tiempo corresponden al drill completo, sin duplicarlos por lado.'),
  ('butt-kicks','Butt Kicks','Talones al glúteo','skill','functional','locomotion',false,
   array['bodyweight'],array['hamstrings','calves'],'{"distance":true,"time":true,"rpe":true}',
   'Corre con pasos cortos flexionando alternativamente las rodillas para acercar los talones a los glúteos.',
   'Mantén el tronco erguido y los apoyos próximos al cuerpo. Recupera el talón sin echar todo el muslo hacia atrás. La distancia o el tiempo describen el drill completo.'),
  ('a-skip','A-Skip','Skipping A','skill','functional','locomotion',false,
   array['bodyweight'],array['hip_flexors','calves','glutes','core'],'{"distance":true,"time":true,"rpe":true}',
   'Avanza con pequeños saltos alternos elevando una rodilla al frente y devolviendo ese pie al suelo bajo el cuerpo.',
   'Mantén el tronco alto y la punta del pie elevada al subir la rodilla. Coordina el brazo contrario y el apoyo bajo la cadera. El coach puede indicar la misma secuencia caminando; la dosis es total.'),
  ('b-skip','B-Skip','Skipping B','skill','functional','locomotion',false,
   array['bodyweight'],array['hip_flexors','hamstrings','calves','core'],'{"distance":true,"time":true,"rpe":true}',
   'Avanza con saltos alternos: eleva la rodilla, extiende después la pierna al frente y recoge el pie hacia el suelo bajo el cuerpo.',
   'Mantén el tronco erguido y el gesto controlado. Tras extender la rodilla, recoge activamente la pierna sin aterrizar lejos de la cadera. La distancia o el tiempo son del drill completo.'),
  ('ankling','Ankling','Pasos cortos de tobillo','skill','functional','locomotion',false,
   array['bodyweight'],array['calves','tibialis_anterior'],'{"distance":true,"time":true,"rpe":true}',
   'Avanza con pasos muy cortos y alternos, rodillas bajas y movimiento controlado de tobillos al apoyar y despegar los pies.',
   'Mantén el cuerpo alto y los contactos próximos a la cadera. Levanta poco los pies y deja que el tobillo acompañe el apoyo. La dosis corresponde al recorrido o tiempo total.'),
  ('lateral-shuffle','Lateral Shuffle','Desplazamiento lateral','skill','functional','locomotion',false,
   array['bodyweight'],array['glutes','adductors','quads','calves'],'{"distance":true,"time":true,"rpe":true}',
   'Desplázate de lado con pasos sucesivos, manteniendo el pecho al frente y sin cruzar los pies.',
   'Flexiona ligeramente caderas y rodillas. Abre con el pie del lado hacia el que avanzas y acerca el otro sin juntar por completo los apoyos. El coach indica las direcciones; no dupliques la distancia por pierna.'),
  ('standing-calf-raise','Calf Raise','Elevación de talones','strength','strength','other',false,
   array['bodyweight','dumbbell','kettlebell','barbell'],array['calves'],'{"reps":true,"time":true,"weight":true,"rpe":true}',
   'Eleva los talones desde el apoyo de la parte delantera de los pies y desciende con control, de pie o sentado según la variante indicada.',
   'Mantén los pies alineados y controla el recorrido del tobillo al subir y bajar. Evita impulsarte con el tronco. El coach elige de pie o sentado, la flexión de rodillas, una o dos piernas y la carga; son variantes de esta identidad.'),
  ('tibialis-raise','Tibialis Raise','Elevación de punta del pie','strength','strength','other',false,
   array['bodyweight','wall'],array['tibialis_anterior'],'{"reps":true,"time":true,"rpe":true}',
   'Con la espalda apoyada en una pared y los pies ligeramente adelantados, eleva la parte delantera de ambos pies manteniendo los talones en el suelo.',
   'Mantén quietas las rodillas y mueve los tobillos. Ajusta la distancia de los pies a la pared para controlar el recorrido. Baja las puntas suavemente sin mover los talones.'),
  ('adductor-rock-back','Adductor Rock-Back','Balanceo de aductor en cuadrupedia','mobility','mobility','other',true,
   array['bodyweight'],array['adductors','hips'],'{"reps":true,"time":true}',
   'En cuadrupedia, extiende una pierna hacia el lateral con el pie apoyado y lleva la pelvis hacia atrás antes de volver al inicio.',
   'Mantén la espalda alargada y la pelvis orientada al suelo. Desplázate desde las caderas sin forzar la rodilla extendida. Completa el gesto en la pierna indicada antes de cambiar de lado.'),
  ('hip-90-90-switch','90/90 Hip Switch','Cambios de cadera 90/90','mobility','mobility','rotation',false,
   array['bodyweight'],array['hips','glutes'],'{"reps":true,"time":true}',
   'Sentado con ambas rodillas flexionadas, cambia la orientación de las piernas de un lado al otro para alternar posiciones de cadera 90/90.',
   'Mantén los pies apoyados y dirige el movimiento desde las caderas. Usa las manos como apoyo si hace falta, sin empujar las rodillas. La dosis es total; cada llegada al otro lado cuenta como un cambio.'),
  ('hamstring-sweep','Walking Hamstring Sweep','Barrido de isquiotibiales caminando','mobility','mobility','locomotion',true,
   array['bodyweight'],array['hamstrings','calves'],'{"reps":true,"distance":true}',
   'Al caminar, apoya un talón delante con la pierna casi extendida, inclina el tronco desde la cadera y barre las manos hacia ese pie antes del siguiente paso.',
   'Flexiona la pierna de apoyo y conserva la espalda alargada. Acerca las manos sin forzar tocar el pie. Si se prescribe por repeticiones son por lado; si se prescribe distancia es el recorrido total.'),
  ('squat-to-stand','Squat-to-Stand','De sentadilla a extensión','mobility','mobility','other',false,
   array['bodyweight'],array['hamstrings','hips','quads'],'{"reps":true,"time":true}',
   'Desde una sentadilla profunda con las manos junto a los pies, eleva la pelvis extendiendo progresivamente las rodillas y vuelve a la sentadilla.',
   'Mantén los pies apoyados y el movimiento controlado. Extiende las piernas solo hasta donde puedas conservar el apoyo y la espalda alargada. La extensión y el regreso forman una repetición.'),
  ('arm-circle','Arm Circles','Círculos de brazos','mobility','mobility','rotation',false,
   array['bodyweight'],array['shoulders'],'{"reps":true,"time":true}',
   'De pie con los brazos abiertos, dibuja círculos con ambos brazos manteniendo el tronco estable.',
   'Mantén los hombros relajados y los codos sin bloquear. Controla el tamaño del círculo sin arquear la espalda. La dirección elegida se mantiene hasta el cambio indicado por el coach.'),
  ('hamstring-stretch','Hamstring Stretch','Estiramiento de isquiotibiales','mobility','mobility','other',true,
   array['bodyweight'],array['hamstrings'],'{"time":true}',
   'Sentado con una pierna extendida y la otra flexionada hacia el lateral, inclina el tronco desde la cadera sobre la pierna extendida y mantén la posición.',
   'Mantén la rodilla extendida sin forzarla y la espalda alargada. Acerca el tronco desde la cadera sin tirar de la punta del pie. Entra y sal del estiramiento de forma gradual.'),
  ('doorway-chest-stretch','Doorway Chest Stretch','Estiramiento de pectoral en marco','mobility','mobility','other',true,
   array['doorframe'],array['chest','shoulders'],'{"time":true}',
   'De pie junto a un marco o apoyo vertical, apoya un antebrazo y gira suavemente el cuerpo en sentido contrario para mantener un estiramiento del pecho.',
   'Usa un apoyo firme y coloca el brazo a una altura cómoda. Mantén el hombro relajado y el tronco erguido. Gira gradualmente sin dejar que el apoyo fuerce el brazo hacia atrás.'),
  ('kneeling-lat-stretch','Kneeling Lat Stretch','Estiramiento dorsal arrodillado','mobility','mobility','other',false,
   array['bodyweight'],array['lats','shoulders'],'{"time":true}',
   'Arrodillado en el suelo, adelanta ambas manos y lleva las caderas hacia los talones mientras alargas los brazos y acercas el pecho al suelo.',
   'Mantén las manos apoyadas y el cuello alineado con el tronco. Alarga desde los hombros sin hundir la zona lumbar. Ajusta el recorrido de las caderas para mantener la postura bajo control.'),
  ('thoracic-extension-foam-roller','Thoracic Extension Over Foam Roller','Extensión torácica sobre rodillo','mobility','mobility','other',false,
   array['foam_roller'],array['thoracic_spine'],'{"reps":true,"time":true}',
   'Tumbado boca arriba con un rodillo transversal bajo la parte alta de la espalda, extiende suavemente el tronco sobre él y vuelve al inicio.',
   'Mantén los pies apoyados y sujeta la cabeza sin tirar del cuello. Extiende la parte alta de la espalda manteniendo las costillas bajo control. Evita desplazar el rodillo hacia la zona lumbar.'),
  ('hamstring-curl','Hamstring Curl','Curl femoral','strength','strength','other',false,
   array['sliders','stability_ball','resistance_band','leg_curl_machine'],array['hamstrings','glutes'],'{"reps":true,"weight":true,"rpe":true}',
   'Tumbado boca arriba con los talones sobre deslizadores, eleva la pelvis, aleja los pies extendiendo las rodillas y recógelos flexionándolas.',
   'Comprueba que los deslizadores se mueven sobre la superficie. Mantén la pelvis elevada sin arquear la espalda y controla la extensión. Usa deslizadores salvo que el coach indique fitball, banda o máquina.'),
  ('lat-pulldown','Lat Pulldown','Jalón al pecho','strength','strength','vertical_pull',false,
   array['cable','resistance_band'],array['lats','biceps','upper_back'],'{"reps":true,"weight":true,"rpe":true}',
   'Sentado en una polea alta, tira del agarre hacia la parte superior del pecho y vuelve extendiendo los brazos de forma controlada.',
   'Ajusta el asiento y el apoyo de los muslos. Dirige los codos hacia abajo sin balancear el tronco ni llevar el agarre detrás de la cabeza. La variante con banda y el agarre concreto los indica el coach.'),
  ('triceps-extension','Triceps Extension','Extensión de tríceps','strength','strength','other',false,
   array['cable','resistance_band','dumbbell'],array['triceps'],'{"reps":true,"weight":true,"rpe":true}',
   'De pie ante una polea alta, sujeta el agarre con ambas manos y extiende los codos hacia abajo antes de volver a flexionarlos.',
   'Mantén los brazos junto al tronco y los hombros quietos. Extiende desde el codo sin empujar con todo el cuerpo. La variante sobre la cabeza, con banda o con mancuerna se describe en la prescripción.'),
  ('split-squat','Split Squat','Sentadilla dividida','strength','strength','lunge',true,
   array['bodyweight','dumbbell','kettlebell','barbell'],array['quads','glutes'],'{"reps":true,"weight":true,"rpe":true}',
   'Con un pie delante y otro detrás, ambos apoyados en el suelo, flexiona las rodillas para bajar la pelvis y vuelve sin cambiar la posición de los pies.',
   'Separa los apoyos lateralmente para equilibrarte. Mantén la rodilla delantera en la dirección del pie y el tronco controlado. Termina el trabajo del lado indicado antes de cambiar; la carga es opcional.'),
  ('back-extension','Back Extension','Extensión de espalda en banco','strength','strength','hinge',false,
   array['back_extension_bench','plate','dumbbell'],array['erectors','glutes','hamstrings'],'{"reps":true,"weight":true,"rpe":true}',
   'En un banco de extensión con pies sujetos y pelvis apoyada, inclina el tronco desde las caderas y elévalo hasta alinearlo con las piernas.',
   'Ajusta el apoyo para que las caderas puedan flexionarse y comprueba la sujeción de los pies. Mantén la espalda alargada y sube sin sobrepasar la línea de las piernas. La carga y cualquier variante las indica el coach.'),
  ('bear-crawl','Bear Crawl','Gateo de oso','skill','functional','locomotion',false,
   array['bodyweight'],array['core','shoulders','quads'],'{"distance":true,"time":true,"rpe":true}',
   'En apoyo de manos y pies con las rodillas cerca del suelo, desplázate adelantando una mano y el pie contrario de forma alterna.',
   'Mantén la espalda estable y las rodillas sin apoyarse. Usa pasos cortos para evitar balancear la pelvis. La distancia o el tiempo se refieren al desplazamiento completo, no a cada lado.')
) as v(slug, name_en, name_es, category, modality, pattern, unilateral,
       equipment, muscles, metrics, description, cues)
on conflict (slug) do nothing;

-- Nombres canónicos ES/EN de las nuevas fichas; siempre globales y activas.
insert into exercise_aliases (exercise_id, term, term_normalized, lang, source)
select e.id, a.term, fahybrid_normalize_term(a.term), a.lang, 'catalog_launch_2026_10'
from exercises e
cross join lateral (values (e.name_es, 'es'), (e.name_en, 'en')) as a(term, lang)
where e.coach_id is null and e.archived_at is null
  and e.source = 'catalog_launch_2026_10'
on conflict (exercise_id, term_normalized) do nothing;

-- Vocabulario habitual: nada de «skipping» sin calificador ni «gemelos» a secas.
insert into exercise_aliases (exercise_id, term, term_normalized, lang, source)
select e.id, a.term, fahybrid_normalize_term(a.term), a.lang, 'catalog_launch_2026_10'
from (values
  ('single-under','comba simple','es'), ('single-under','saltos simples de comba','es'),
  ('single-under','salto de comba','es'), ('single-under','comba','es'),
  ('single-under','single unders','en'), ('single-under','jump rope','en'),
  ('jumping-jack','jumping jacks','en'), ('jumping-jack','salto de apertura','es'),
  ('high-knees','rodillas arriba','es'), ('high-knees','skipping alto','es'),
  ('butt-kicks','taloneo','es'), ('butt-kicks','talones al gluteo','es'),
  ('butt-kicks','heel flicks','en'),
  ('a-skip','a skip','en'), ('a-skip','a skips','en'),
  ('a-skip','skipping a caminando','es'), ('a-skip','a march','en'),
  ('b-skip','b skip','en'), ('b-skip','b skips','en'),
  ('ankling','pasos de tobillo','es'), ('ankling','ankle dribbles','en'),
  ('lateral-shuffle','pasos laterales sin banda','es'), ('lateral-shuffle','side shuffle','en'),
  ('standing-calf-raise','elevaciones de gemelo','es'), ('standing-calf-raise','elevacion de gemelos','es'),
  ('standing-calf-raise','calf raise','en'), ('standing-calf-raise','calf raises','en'),
  ('standing-calf-raise','standing calf raise','en'),
  ('standing-calf-raise','elevacion de talones de pie','es'),
  ('standing-calf-raise','elevacion de talones con rodilla flexionada','es'),
  ('standing-calf-raise','elevacion de talones sentado','es'),
  ('standing-calf-raise','gemelo sentado','es'),
  ('standing-calf-raise','elevaciones de soleo','es'), ('standing-calf-raise','bent-knee calf raise','en'),
  ('standing-calf-raise','seated calf raise','en'),
  ('tibialis-raise','elevaciones de tibial','es'), ('tibialis-raise','elevacion del tibial anterior','es'),
  ('tibialis-raise','tib raises','en'),
  ('adductor-rock-back','balanceo de aductor','es'), ('adductor-rock-back','adductor rock back','en'),
  ('hip-90-90-switch','transiciones 90/90','es'), ('hip-90-90-switch','cambios 90 90','es'),
  ('hip-90-90-switch','hip switches','en'), ('hip-90-90-switch','90 90 hip switch','en'),
  ('hamstring-sweep','barrido de isquios','es'), ('hamstring-sweep','hamstring sweeps','en'),
  ('squat-to-stand','sentadilla a extension','es'), ('squat-to-stand','squat to stand','en'),
  ('arm-circle','circulos de hombros','es'), ('arm-circle','arm circle','en'),
  ('hamstring-stretch','estiramiento de isquios','es'), ('hamstring-stretch','seated hamstring stretch','en'),
  ('doorway-chest-stretch','estiramiento de pectoral','es'), ('doorway-chest-stretch','chest stretch','en'),
  ('kneeling-lat-stretch','estiramiento de dorsales','es'), ('kneeling-lat-stretch','lat stretch','en'),
  ('thoracic-extension-foam-roller','extension dorsal sobre rodillo','es'),
  ('thoracic-extension-foam-roller','foam roller thoracic extension','en'),
  ('hamstring-curl','curl de isquiotibiales','es'), ('hamstring-curl','curl femoral deslizante','es'),
  ('hamstring-curl','sliding leg curl','en'), ('hamstring-curl','leg curl','en'),
  ('lat-pulldown','jalon dorsal','es'), ('lat-pulldown','lat pull down','en'),
  ('triceps-extension','extension de triceps en polea','es'), ('triceps-extension','triceps pushdown','en'),
  ('split-squat','split squat estatico','es'), ('split-squat','sentadilla en tijera','es'),
  ('back-extension','hiperextension en banco','es'), ('back-extension','back extensions','en'),
  ('bear-crawl','gateo del oso','es'), ('bear-crawl','bear crawls','en')
) as a(slug, term, lang)
join exercises e on e.slug = a.slug
where e.coach_id is null and e.archived_at is null
on conflict (exercise_id, term_normalized) do nothing;
